// Command oraclegen emits oracle-comparison test skeletons from go.yaml.
//
// For every spec entry that carries a Python provenance (py:) and is fully
// typed — a non-blank return: and a concrete type on every parameter — it
// prints one TestOracle_<Pkg>_<Name> function. Each skeleton:
//
//   - constructs the receiver (for methods) via its planned New<Recv>
//     constructor, when one exists in the spec, else leaves a TODO;
//   - declares each parameter as its Go zero value;
//   - calls the method/function with those args;
//   - leaves a TODO to compare against `goof mmgroup.py "<py>(...)"`.
//
// This is scaffolding, not a finished suite: the zero-value args and the
// oracle comparison are placeholders for a human to fill in. The output is
// valid, compilable-shaped Go (it parses and gofmts; it will not compile
// until the referenced cgt symbols exist), so it can be redirected into a
// *_oracle_test.go file as a starting point.
//
// Usage:
//
//	go run -C _api ./cmd/oraclegen                 # all packages, to stdout
//	go run -C _api ./cmd/oraclegen -pkg mm         # one package only
//	go run -C _api ./cmd/oraclegen -recv MM        # one receiver only
//	go run -C _api ./cmd/oraclegen -package mmtest # emitted package clause
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"patel.codes/cgt/_api/spec"
)

func main() {
	specPath := flag.String("spec", "go.yaml", "path to the go.yaml spec")
	pkgFilter := flag.String("pkg", "", "restrict to spec package (e.g. mm)")
	recvFilter := flag.String("recv", "", "restrict to receiver type (e.g. MM)")
	goPackage := flag.String("package", "cgt_oracle", "package clause for emitted file")
	flag.Parse()

	s, err := spec.Load(*specPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "oraclegen: loading %s: %v\n", *specPath, err)
		os.Exit(1)
	}

	out := os.Stdout
	emitHeader(out, *goPackage)

	ctors := constructors(s)
	var emitted int
	for _, fn := range s.AllFuncs() {
		if *pkgFilter != "" && fn.Pkg != *pkgFilter {
			continue
		}
		if *recvFilter != "" && fn.Recv != *recvFilter {
			continue
		}
		if !qualifies(fn) {
			continue
		}
		emitSkeleton(out, fn, ctors)
		emitted++
	}
	fmt.Fprintf(out, "\n// emitted %d oracle skeletons\n", emitted)
}

// qualifies reports whether an entry is eligible for a skeleton: it must have
// a Python provenance, a non-blank return type, and a concrete type on every
// parameter (deferred/blank types cannot be zero-valued).
func qualifies(fn spec.Func) bool {
	if fn.Py == "" || fn.Return == "" {
		return false
	}
	for _, p := range fn.Params {
		if p.Type == "" {
			return false
		}
	}
	return true
}

// constructors maps a receiver type to its planned New<Recv> constructor
// entry, when the spec defines one. Used to construct the receiver in a
// method skeleton.
func constructors(s *spec.Spec) map[string]spec.Func {
	out := make(map[string]spec.Func)
	for _, fn := range s.AllFuncs() {
		if recv, ok := strings.CutPrefix(fn.Name, "New"); ok {
			// Prefer the bare New<Recv>; do not let New<Recv>FromX override it.
			if _, seen := out[recv]; !seen {
				out[recv] = fn
			}
		}
	}
	return out
}

func emitHeader(out *os.File, goPackage string) {
	fmt.Fprintf(out, `// Code generated by oraclegen from go.yaml. EDIT FREELY.
//
// These are oracle-comparison test SKELETONS. Each test constructs a value,
// calls one planned cgt method/function with zero-value arguments, and
// leaves a TODO to compare the result against the mmgroup oracle via
// `+"`goof mmgroup.py`"+`. Fill in real inputs and assertions per test.

package %s

import "testing"
`, goPackage)
}

func emitSkeleton(out *os.File, fn spec.Func, ctors map[string]spec.Func) {
	testName := "TestOracle_" + capitalize(fn.Pkg) + "_" + fn.Name
	fmt.Fprintf(out, "\nfunc %s(t *testing.T) {\n", testName)

	// Receiver construction for methods.
	recvVar := ""
	if fn.Recv != "" {
		recvVar = "recv"
		if ctor, ok := ctors[fn.Recv]; ok {
			fmt.Fprintf(out, "\t// TODO: supply real arguments to the constructor.\n")
			fmt.Fprintf(out, "\t%s := %s(%s) // planned constructor for %s\n",
				recvVar, ctor.Name, zeroArgs(ctor.Params), fn.Recv)
		} else {
			fmt.Fprintf(out, "\t// TODO: no New%s constructor in spec; construct %s manually.\n",
				fn.Recv, fn.Recv)
			fmt.Fprintf(out, "\tvar %s *%s\n", recvVar, fn.Recv)
		}
	}

	// Argument zero values.
	args := zeroArgs(fn.Params)

	// The call.
	fmt.Fprintf(out, "\t// TODO: replace zero-value args with a real test case.\n")
	if fn.Recv != "" {
		fmt.Fprintf(out, "\tgot := %s.%s(%s)\n", recvVar, fn.Name, args)
	} else {
		fmt.Fprintf(out, "\tgot := %s.%s(%s)\n", fn.Pkg, fn.Name, args)
	}
	fmt.Fprintf(out, "\t_ = got // return type: %s\n", fn.Return)

	// Oracle comparison TODO, carrying the py provenance verbatim.
	fmt.Fprintf(out, "\t// Oracle: compare got against\n")
	fmt.Fprintf(out, "\t//   goof mmgroup.py \"print(%s(...))\"\n", fn.Py)
	fmt.Fprintf(out, "\tt.Skip(\"oracle skeleton: fill in inputs and assertion\")\n")
	fmt.Fprintf(out, "}\n")
}

// zeroArgs renders a comma-separated list of Go zero-value literals, one per
// parameter, suitable as a call argument list.
func zeroArgs(params []spec.Param) string {
	if len(params) == 0 {
		return ""
	}
	parts := make([]string, len(params))
	for i, p := range params {
		parts[i] = zeroValue(p.Type)
	}
	return strings.Join(parts, ", ")
}

// zeroValue returns a Go expression evaluating to the zero value of a type
// named in the spec. Slices, maps, pointers, and interfaces are nil;
// numeric and string types use their bare zero literal; anything composite
// or unrecognized falls back to a conversion of the zero literal so the
// skeleton still parses.
func zeroValue(typ string) string {
	typ = strings.TrimSpace(typ)
	switch {
	case typ == "":
		return "nil /* deferred */"
	case strings.HasPrefix(typ, "[]"), strings.HasPrefix(typ, "*"),
		strings.HasPrefix(typ, "map["), typ == "any", typ == "error":
		return "nil"
	case typ == "string":
		return `""`
	case typ == "bool":
		return "false"
	case strings.HasPrefix(typ, "int"), strings.HasPrefix(typ, "uint"),
		strings.HasPrefix(typ, "float"), typ == "byte", typ == "rune":
		return typ + "(0)"
	case strings.HasPrefix(typ, "[") && strings.Contains(typ, "]"):
		// Fixed-size array, e.g. [4]int — zero value is the composite literal.
		return typ + "{}"
	default:
		// Named/struct type: a composite literal zero value.
		return typ + "{}"
	}
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
