package main

// order_vector.go emits the precomputed order vector
// table orderVectorTable, the Go counterpart of the C
// table ORDER_VECTOR in mm_order_vector.c
// (ORDER_VECTOR_DATA).
//
// Unlike the other generators in this directory, this
// table is not derived from the Golay code or any
// algebraic seed: it is the precomputed order vector
// v_1 of the representation rho_15, an opaque blob of
// 24720 uint32 words. The generator therefore carries
// the values verbatim in the embedded data file
// order_vector_data.txt and re-emits them in the
// house table layout, so the checked-in
// monster_order_gen.go stays byte-for-byte
// reproducible.
//
// Provenance:
//
//	mmgroup/src/mmgroup/dev/c_files/mm_order_vector.c
//	  (table ORDER_VECTOR / ORDER_VECTOR_DATA)

import (
	"bytes"
	_ "embed"
	"fmt"
	"go/format"
	"io"
	"strconv"
	"strings"
)

// orderVectorData holds the verbatim ORDER_VECTOR
// words as whitespace- and comma-separated 0x... hex
// tokens, one source row per line.
//
//go:embed order_vector_data.txt
var orderVectorData string

// orderTagData holds the verbatim
// MM_ORDER_VECTOR_TAG_DATA words (file
// mm_order_vector.c) as whitespace- and
// comma-separated 0x... hex tokens. These describe
// how to recover a G_x0 element from the image of the
// order vector under that element.
//
//go:embed order_tag_data.txt
var orderTagData string

// ovEntries is the expected number of words in
// orderVectorTable: 72 tag-(A,B,C) rows of 3 words,
// 759 tag-T rows of 8 words and 6144 tag-X rows of 3
// words. C OFS_X + 6144*3.
const ovEntries = 72*3 + 759*8 + 6144*3

// ovTagEntries is the expected number of words in
// orderTagTable. C sizeof(MM_ORDER_VECTOR_TAG_DATA).
// Layout (C VECTOR_LENGTHS): WATERMARK_PERM 24,
// TAGS_X 24, SOLVE_X 24, TAGS_Y 11, SOLVE_Y 11,
// TAG_SIGN 1, NORM_A 1, then 43 words of xsp2co1
// element data unused by the membership test.
const ovTagEntries = 24 + 24 + 24 + 11 + 11 + 1 + 1 + 43

// genOrderVector parses the embedded ORDER_VECTOR
// words and writes monster_order_gen.go to w.
//
// The cgtDir argument is unused: the table is carried
// verbatim, with no golden file to locate. The
// parameter is present so every generator shares one
// dispatch signature.
//
// genOrderVector returns an error if the embedded data
// is malformed, if it does not hold exactly ovEntries
// words, or if the emitted source does not gofmt.
func genOrderVector(w io.Writer, _ string) error {
	vals, err := parseHexWords(orderVectorData)
	if err != nil {
		return err
	}
	if len(vals) != ovEntries {
		return fmt.Errorf("order vector has %d words, want %d",
			len(vals), ovEntries)
	}
	tagVals, err := parseHexWords(orderTagData)
	if err != nil {
		return err
	}
	if len(tagVals) != ovTagEntries {
		return fmt.Errorf("order tag data has %d words, want %d",
			len(tagVals), ovTagEntries)
	}

	packed := packOrderVector(vals)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cgt/_gen; DO NOT EDIT.\n")
	buf.WriteString("//\n")
	buf.WriteString("// Precomputed order vector v_1 of the representation\n")
	buf.WriteString("// rho_15, derived from the C table ORDER_VECTOR in\n")
	buf.WriteString("// mm_order_vector.c (ORDER_VECTOR_DATA). The C words are\n")
	buf.WriteString("// pre-packed here into the runtime p=15 SWAR layout (two\n")
	buf.WriteString("// uint32 table words per uint64 via the C pair(h,l)\n")
	buf.WriteString("// macro), so loadOrderVector copies the words straight\n")
	buf.WriteString("// into place with no shuffle. The layout is 72 rows of\n")
	buf.WriteString("// 2 words (tags A,B,C), then 759 rows of 4 words (tag\n")
	buf.WriteString("// T), then 6144 rows of 2 words (tag X).\n")
	buf.WriteString("//\n")
	buf.WriteString("// orderTagTable is a verbatim copy of the C table\n")
	buf.WriteString("// MM_ORDER_VECTOR_TAG_DATA in the same file; it drives\n")
	buf.WriteString("// recovery of a G_x0 element from the image of the\n")
	buf.WriteString("// order vector under that element.\n\n")
	buf.WriteString("package cgt\n")
	writeHexTable(&buf, "orderVectorTable", "...", "uint64", 16, valsPerLine, packed)
	writeHexTable(&buf, "orderTagTable", "...", "uint32", 8, valsPerLine, tagVals)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt: %w\n%s", err, buf.Bytes())
	}
	if _, err := w.Write(src); err != nil {
		return fmt.Errorf("write: %w", err)
	}
	return nil
}

// packOrderVector pre-packs the verbatim ORDER_VECTOR
// uint32 words into the runtime p=15 SWAR layout, the
// shuffle the C load24/load64 helpers performed at
// runtime. Each pair of table words (h, l) becomes one
// uint64 via pair(h, l) = h<<32 | l.
//
// The three regions are packed in place: 72 tag-(A,B,C)
// rows of 3 words become 2 words each (pair(w1,w0),
// pair(0,w2)); 759 tag-T rows of 8 words become 4 words
// each (four pairs); 6144 tag-X rows of 3 words become 2
// words each, like the A,B,C rows. The packed regions
// are concatenated in the same order, so loadOrderVector
// copies each region straight to its destination offset.
func packOrderVector(vals []uint64) []uint64 {
	pair := func(h, l uint64) uint64 { return (h << 32) | l }
	out := make([]uint64, 0, 72*2+759*4+6144*2)

	// load24 regions and the load64 region read words at
	// these source offsets (in uint32 units).
	const (
		ofsABC = 0
		ofsT   = 72 * 3
		ofsX   = ofsT + 759*8
	)

	pack24 := func(srcOfs, n int) {
		src := vals[srcOfs:]
		for i := 0; i < n; i++ {
			out = append(out, pair(src[1], src[0]), pair(0, src[2]))
			src = src[3:]
		}
	}
	pack64 := func(srcOfs, n int) {
		src := vals[srcOfs:]
		for i := 0; i < 2*n; i++ {
			out = append(out, pair(src[1], src[0]), pair(src[3], src[2]))
			src = src[4:]
		}
	}

	pack24(ofsABC, 72)
	pack64(ofsT, 759)
	pack24(ofsX, 3*2048)
	return out
}

// parseHexWords splits data into 0x... hex tokens
// (whitespace- and comma-separated) and parses each as
// a uint32, returning the words as []uint64 for
// writeHexTable.
func parseHexWords(data string) ([]uint64, error) {
	fields := strings.FieldsFunc(data, func(r rune) bool {
		return r == ',' || r == ' ' || r == '\t' || r == '\n' || r == '\r'
	})
	vals := make([]uint64, 0, len(fields))
	for _, f := range fields {
		v, err := strconv.ParseUint(strings.TrimPrefix(f, "0x"), 16, 32)
		if err != nil {
			return nil, fmt.Errorf("parse hex word %q: %w", f, err)
		}
		vals = append(vals, v)
	}
	return vals, nil
}
