package main

// order_vector.go emits the precomputed order vector
// table orderVectorTable, the Go counterpart of the C
// table ORDER_VECTOR in mm_order_vector.c
// (ORDER_VECTOR_DATA).
//
// Unlike the other generators in this directory, this
// table is not derived from the Golay code or any
// algebraic seed: it is the precomputed order vector
// v_1 of the representation rho_15, an opaque blob of
// 24720 uint32 words. The generator therefore carries
// the values verbatim in the embedded data file
// order_vector_data.txt and re-emits them in the
// house table layout, so the checked-in
// monster_order_gen.go stays byte-for-byte
// reproducible.
//
// Provenance:
//
//	mmgroup/src/mmgroup/dev/c_files/mm_order_vector.c
//	  (table ORDER_VECTOR / ORDER_VECTOR_DATA)

import (
	"bytes"
	_ "embed"
	"fmt"
	"go/format"
	"io"
	"strconv"
	"strings"
)

// orderVectorData holds the verbatim ORDER_VECTOR
// words as whitespace- and comma-separated 0x... hex
// tokens, one source row per line.
//
//go:embed order_vector_data.txt
var orderVectorData string

// ovEntries is the expected number of words in
// orderVectorTable: 72 tag-(A,B,C) rows of 3 words,
// 759 tag-T rows of 8 words and 6144 tag-X rows of 3
// words. C OFS_X + 6144*3.
const ovEntries = 72*3 + 759*8 + 6144*3

// genOrderVector parses the embedded ORDER_VECTOR
// words and writes monster_order_gen.go to w.
//
// The cgtDir argument is unused: the table is carried
// verbatim, with no golden file to locate. The
// parameter is present so every generator shares one
// dispatch signature.
//
// genOrderVector returns an error if the embedded data
// is malformed, if it does not hold exactly ovEntries
// words, or if the emitted source does not gofmt.
func genOrderVector(w io.Writer, _ string) error {
	vals, err := parseOrderVector(orderVectorData)
	if err != nil {
		return err
	}
	if len(vals) != ovEntries {
		return fmt.Errorf("order vector has %d words, want %d",
			len(vals), ovEntries)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cgt/_gen; DO NOT EDIT.\n")
	buf.WriteString("//\n")
	buf.WriteString("// Precomputed order vector v_1 of the representation\n")
	buf.WriteString("// rho_15, a verbatim copy of the C table ORDER_VECTOR\n")
	buf.WriteString("// in mm_order_vector.c (ORDER_VECTOR_DATA). The layout\n")
	buf.WriteString("// is 72 rows of 3 words (tags A,B,C), then 759 rows of\n")
	buf.WriteString("// 8 words (tag T), then 6144 rows of 3 words (tag X).\n\n")
	buf.WriteString("package cgt\n")
	writeHexTable(&buf, "orderVectorTable", "...", "uint32", 8, valsPerLine, vals)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt: %w\n%s", err, buf.Bytes())
	}
	if _, err := w.Write(src); err != nil {
		return fmt.Errorf("write: %w", err)
	}
	return nil
}

// parseOrderVector splits data into 0x... hex tokens
// (whitespace- and comma-separated) and parses each as
// a uint32, returning the words as []uint64 for
// writeHexTable.
func parseOrderVector(data string) ([]uint64, error) {
	fields := strings.FieldsFunc(data, func(r rune) bool {
		return r == ',' || r == ' ' || r == '\t' || r == '\n' || r == '\r'
	})
	vals := make([]uint64, 0, ovEntries)
	for _, f := range fields {
		v, err := strconv.ParseUint(strings.TrimPrefix(f, "0x"), 16, 32)
		if err != nil {
			return nil, fmt.Errorf("parse order vector word %q: %w", f, err)
		}
		vals = append(vals, v)
	}
	return vals, nil
}
