package cgt

// This file ports leech2_orbits_raw from
// mmgroup/src/mmgroup/structures/xleech2.py, the driver
// that computes the orbits of the Leech lattice mod 2
// (V = GF(2)^24) under the action of a subgroup H of
// G_x0, given by a list of monster generators. It uses the
// orbit-array engine in ufind_lin2.go.

// Leech2OpWordMatrix24 returns the 24 x 24 bit matrix
// describing the (sign-free) action of the word g of
// monster generators on the Leech lattice mod 2. Row i of
// the returned matrix is the image of the i-th basis
// vector 1 << i. If back is true the inverse action is
// used. Leech2OpWordMatrix24 panics if any atom of g takes
// the word out of G_x0 (e.g. a nonzero triality atom).
// Mirrors gen_leech2_op_word_matrix24.
func Leech2OpWordMatrix24(g []uint32, back bool) []uint32 {
	a := make([]uint32, 24)
	for i := range a {
		a[i] = 1 << uint(i)
	}
	if genLeech2OpWordLeech2Many(a, g, back) < 0 {
		panic("cgt: Leech2OpWordMatrix24: word not in G_x0")
	}
	return a
}

// Leech2OrbitsResult is the partition of the Leech lattice
// mod 2 returned by Leech2OrbitsRaw. NSets is the number of
// orbits. Data holds all 2^24 vectors of GF(2)^24, grouped
// by orbit, and Indices (length NSets+1) gives the orbit
// boundaries: orbit i is Data[Indices[i]:Indices[i+1]]. The
// vectors within each orbit are sorted, and the orbits are
// sorted by their smallest element. Map, populated only
// when Leech2OrbitsRaw is called with map_ = true, maps
// every vector to the smallest vector in its orbit (else
// nil). Mirrors the (n_sets, indices, data[, map]) tuple of
// leech2_orbits_raw.
type Leech2OrbitsResult struct {
	NSets   int
	Indices []uint32
	Data    []uint32
	Map     []uint32
}

// leech2OrbitGen is the interface a generator passed to
// Leech2OrbitsRaw must satisfy: it must expose its monster
// atom representation. Both *MM and *XLeech2 provide this
// via Mmdata in the cgt surface.
type leech2OrbitGen interface {
	Mmdata() []uint32
}

// Leech2OrbitsRaw computes the orbits of the Leech lattice
// mod 2 under the action of the subgroup H of G_x0
// generated by gList. Each element of gList must be a
// monster element exposing its atom representation through
// Mmdata (e.g. *MM). A vector of the Leech lattice mod 2 is
// encoded as an integer (the XLeech2 encoding with the sign
// bit cleared).
//
// If map_ is false the returned result has a nil Map; if
// map_ is true Map is the 2^24-entry minimal-representative
// map. Leech2OrbitsRaw panics if a generator's word leaves
// G_x0. Mirrors leech2_orbits_raw.
//
// Note: the upstream Python leech2_orbits_raw passes a
// fourth argument to gen_ufind_lin2_add that the compiled
// binding rejects, so the Python function cannot run as
// written; this port follows the documented intent (the
// three-argument add).
func Leech2OrbitsRaw(gList []leech2OrbitGen, map_ bool) Leech2OrbitsResult {
	const n = uint32(24)
	nG := uint32(len(gList))
	lenA := uint32(UFindLin2Size(n, nG))
	a := make([]uint32, lenA)
	UFindLin2Init(a, lenA, n, nG)
	for _, g := range gList {
		md := g.Mmdata()
		ag := Leech2OpWordMatrix24(md, false)
		UFindLin2Add(a, ag, uint32(len(ag)))
	}
	lData := uint32(1) << uint(UFindLin2Dim(a))
	nSets := uint32(UFindLin2NOrbits(a))
	data := make([]uint32, lData)
	indices := make([]uint32, nSets+1)
	UFindLin2Orbits(a, data, lData, indices, nSets+1)
	res := Leech2OrbitsResult{
		NSets:   int(nSets),
		Indices: indices,
		Data:    data,
	}
	if map_ {
		m := make([]uint32, lData)
		UFindLin2GetMap(a, m, lData)
		res.Map = m
	}
	return res
}
