package cgt

import (
	"math/bits"
)

// This file is a faithful port of the C module
// gen_ufind_lin2.c (with its auxiliary header
// gen_ufind_lin2_aux.h) from the mmgroup project.
//
// The functions deal with the operation of a group
// G as a permutation group on the vector space
// V = GF(2)^n for n <= 24. The group is generated by
// a set of n x n bit matrices acting on V by right
// multiplication. These functions compute orbits on
// V under the action of G, representatives and sizes
// of these orbits, and Schreier vectors so that an
// element of G mapping a vector in an orbit to any
// other vector in the same orbit can be found.
//
// All information about the group is stored in an
// opaque packed []uint32 "orbit array" a. The packed
// layout is preserved byte-for-byte against the C
// implementation for oracle parity. The internal
// structure of a is documented in the unexported
// lin2Type and the helpers below.
//
// C functions return negative error codes. Here the
// internal helpers return those same negative codes
// (as int32) so the packed-array status bookkeeping
// matches the C exactly; the exported UFindLin2*
// wrappers panic with a descriptive message on a
// negative status, as documented in each wrapper.

// Error codes, matching the enum in
// gen_union_find.ske. Negative values returned by the
// internal helpers carry these meanings.
const (
	errGenUfindMem      int32 = -1  // Out of memory
	errGenUfindUFLarge  int32 = -2  // Too many entries for union-find
	errGenUfindInLarge  int32 = -3  // Input parameter too large
	errGenUfindOutShort int32 = -4  // Output buffer too short
	errGenUfindEntryUF  int32 = -5  // Entry not in union-find table
	errGenUfindTableUF  int32 = -6  // Union-find table too large
	errGenUfindLin2Dim  int32 = -7  // Dimension n of GF(2)^n is 0 or too large
	errGenUfindLin2Gen  int32 = -8  // Too many generators
	errGenUfindInverse  int32 = -9  // Generator matrix is not invertible
	errGenUfindState    int32 = -10 // Buffer not in correct state
	errGenUfindDupl     int32 = -11 // Duplicate entry in union-find table

	// -100 .. -199 are internal errors in gen_union_find.c.
	errGenUfindIntTable int32 = -100
	// -200 .. -299 are internal errors in gen_ufind_lin2.c.
	errGenUfindIntLin2 int32 = -200
)

// Layout constants from gen_ufind_lin2_aux.h.
const (
	lin2LenHeader  = 6    // Length of header of the orbit array
	lin2MaxStatus  = 2    // Maximum good status
	lin2MaxN       = 24   // Maximum dimension n of GF(2)^n
	lin2MaxNG      = 127  // Maximum number of generators
	lin2Compressed = 0x10 // Status indicating a compressed orbit array

	lin2Magic = 0x1fecd173 // Header hash seed
	lin2AMul  = 0x5ac83257 // Header hash multiplier
)

// lin2GeneratorSize returns the number of 32-bit
// integers required to store k generators of a group
// acting on a vector space over GF(2) of dimension n.
func lin2GeneratorSize(n, k uint32) uint32 {
	return 2 * (n + 1) * k
}

// lin2Type is the in-memory interpretation of the
// header and table pointers of a packed orbit array a.
// The slices p_t, p_o, p_g are subslices of a.
type lin2Type struct {
	status   int32  // Status of the array
	n        uint32 // Dimension n of GF(2)^n
	nMaxG    uint32 // Maximum number of generators of G
	nG       uint32 // Number of generators of G
	nOrbits  uint32 // Number of G orbits in GF(2)^n
	nVectors uint32 // Number of vectors, usually 1 << n
	pT       []uint32
	pO       []uint32
	pG       []uint32
}

// loadLin2Info copies the header and slices the table
// pointers out of the orbit array a into s. It returns
// the status stored in a[0]; a negative value
// indicates an error. This mirrors load_lin2_info.
func loadLin2Info(a []uint32, s *lin2Type) int32 {
	if a == nil {
		return errGenUfindIntLin2 - 1
	}
	s.status = int32(a[0])
	s.n = a[1]
	s.nMaxG = a[2]
	s.nG = a[3]
	s.nOrbits = a[4]
	s.nVectors = a[5]
	pt := a[lin2LenHeader:]
	s.pT = pt
	if s.status == lin2Compressed {
		s.pO = pt[s.nVectors:]
		s.pG = s.pO[2*s.nOrbits:]
	} else {
		sz := uint32(1) << s.n
		s.pO = pt[sz:]
		s.pG = s.pO[sz:]
	}
	return s.status
}

// storeLin2Info copies the header from s back into the
// orbit array a. It returns the status, a negative
// value indicating an error. This mirrors
// store_lin2_info, including the guard that refuses to
// overwrite an array already in an error state.
func storeLin2Info(s *lin2Type, a []uint32) int32 {
	if a == nil {
		return errGenUfindIntLin2 - 1
	}
	if int32(a[0]) < 0 {
		return int32(a[0])
	}
	a[0] = uint32(s.status)
	a[1] = s.n
	a[2] = s.nMaxG
	a[3] = s.nG
	a[4] = s.nOrbits
	a[5] = s.nVectors
	return s.status
}

// lin2Error records a negative status into a[0] if a
// is not already in an error state, and returns status.
// This mirrors lin2_error.
func lin2Error(a []uint32, status int32) int32 {
	if status >= 0 {
		return status
	}
	if a != nil {
		if int32(a[0]) >= 0 {
			a[0] = uint32(status)
		}
	}
	return status
}

// checkOutBuf32 returns 0 if a buffer of len uint32s
// can store minLen uint32s, and a negative value
// otherwise. This mirrors check_out_buf32. (A nil
// buffer or minLen with bit 31 set is rejected.)
func checkOutBuf32(buf []uint32, length, minLen uint32) int32 {
	if buf == nil || minLen&0x80000000 != 0 || length < minLen {
		return errGenUfindOutShort
	}
	return 0
}

// lin2Generator returns the subslice of s.pG holding
// the i-th generator (i even) or its inverse (i odd).
// Each generator occupies n+1 uint32s. Mirrors
// lin2_generator.
func lin2Generator(s *lin2Type, i uint32) []uint32 {
	off := i * (s.n + 1)
	return s.pG[off:]
}

// vmatmulAff transforms a vector with an affine
// transformation v -> v*A + b. Row i of A is m[i] and
// b is m[n]. Mirrors vmatmul_aff.
func vmatmulAff(v uint32, m []uint32, n uint32) uint32 {
	w := m[n]
	for i := uint32(0); i < n; i++ {
		w ^= m[i] & (0 - ((v >> i) & 1))
	}
	return w & ((1 << n) - 1)
}

// matInverseAff computes the inverse of the affine
// transformation on GF(2)^n given by m (length n+1)
// and stores it in mInv (length n+1). Returns 0 on
// success and a negative value if m is not invertible.
// Mirrors mat_inverse_aff.
func matInverseAff(m []uint32, n uint32, mInv []uint32) int32 {
	var a [lin2MaxN + 1]uint64
	if n == 0 || n > lin2MaxN {
		return errGenUfindInverse
	}
	mask := uint32(1)<<n - 1
	for i := uint32(0); i <= n; i++ {
		a[i] = uint64(m[i] & mask)
	}
	a[n] |= uint64(1) << n
	if bitmatrix64Inv(a[:n+1], n+1) != 0 {
		return errGenUfindInverse
	}
	for i := uint32(0); i <= n; i++ {
		mInv[i] = uint32(a[i] & uint64(mask))
	}
	return 0
}

// findNextBitSet returns the index of the lowest bit
// set to one in bitmap at or above startIndex. At
// least one bit at index >= startIndex must be set.
// Mirrors find_next_bit_set; uses TrailingZeros64
// instead of the deBruijn table.
func findNextBitSet(bitmap []uint64, startIndex uint32) uint32 {
	pb := startIndex >> 6
	v := bitmap[pb] & (0 - (uint64(1) << (startIndex & 63)))
	for v == 0 {
		pb++
		v = bitmap[pb]
	}
	return (pb << 6) + uint32(bits.TrailingZeros64(v))
}

// writeLengthInfo encodes the length information length
// in the upper 8 bits of the entries of the (sub)slice
// a, using at most length entries. Legal values are
// 1 <= length < 0x80000000. Mirrors write_length_info.
func writeLengthInfo(a []uint32, length uint32) {
	var idx int
	gt := uint32(0)
	if length > 0x3f {
		gt = 1
	}
	x := 0x80 | (gt << 6) | (length & 0x3f)
	a[idx] = (a[idx] & 0x00ffffff) | (x << 24)
	idx++
	length >>= 6
	for length != 0 {
		gt = 0
		if length > 0x3f {
			gt = 1
		}
		x = (gt << 6) | (length & 0x3f)
		a[idx] = (a[idx] & 0x00ffffff) | (x << 24)
		idx++
		length >>= 6
	}
}

// readLengthInfo returns the length information
// previously encoded by writeLengthInfo in the upper 8
// bits of (sub)slice a. Returns a negative value on
// error. Mirrors read_length_info.
func readLengthInfo(a []uint32) int32 {
	idx := 0
	x := (a[idx] >> 24) & 0xff
	idx++
	if x&0x80 == 0 {
		return -1
	}
	length := x & 0x3f
	for sh := uint32(6); sh < 24 && (x&0x40) != 0; sh += 6 {
		x = (a[idx] >> 24) & 0xff
		idx++
		if x&0x80 != 0 {
			return errGenUfindIntLin2 - 1
		}
		length += (x & 0x3f) << sh
	}
	return int32(length)
}

// store64Gen expands a generator g0 and its inverse g1
// into the lookup table o (length 0x300) used for fast
// vector-by-matrix products over the doubled (64-bit)
// representation. Mirrors store64_gen.
//
// For n <= 24 and a vector v,
//
//	v*G = o[byte(0,v)] ^ o[0x100+byte(1,v)] ^ o[0x200+byte(2,v)]
//
// where the high 32 bits carry the image under g1 and
// the low 32 bits carry the image under g0.
func store64Gen(o []uint64, n uint32, g0, g1 []uint32) {
	for i := range o[:0x300] {
		o[i] = 0
	}
	mask := uint64(uint32(1)<<n - 1)
	mask = (mask << 32) + mask
	v0 := uint64(g1[n])
	v0 = ((v0 << 32) + uint64(g0[n])) & mask
	o[0] = v0
	gi0, gi1 := 0, 0 // read cursors into g0, g1
	base := 0        // current 0x100 block base into o
	for i := uint32(0); i < 24; i += 8 {
		if n > i {
			var gHi uint64
			var jHi uint32
			jmax := n - i
			if jmax > 8 {
				jmax = 8
			}
			for j := uint32(1); j < (uint32(1) << jmax); j++ {
				if j&(j-1) == 0 { // j is a power of 2
					gHi = uint64(g1[gi1])
					gi1++
					gHi = ((gHi << 32) + uint64(g0[gi0])) & mask
					gi0++
					jHi = j
				}
				o[base+int(j)] = gHi ^ o[base+int(j-jHi)]
			}
		}
		base += 0x100
	}
}

// computePartition computes the partition of S(l_t)
// (with l_t = 1 << dim) stored in table into a list of
// lists in the slice mapOut. lInd must be an upper
// bound for the number of orbits. It returns the actual
// number of orbits on success and a negative value on
// failure. Mirrors compute_partition.
func computePartition(table []uint32, dim uint32, mapOut []uint32, lInd uint32) int32 {
	lT := uint32(1) << dim
	mask := lT - 1
	var i, j, last, fst, p, lastN uint32
	status := int32(-1)

	if dim > 24 {
		return errGenUfindLin2Dim
	}
	// next has length lT + lInd; ind has length lInd.
	next := make([]uint32, lT+lInd)
	ind := make([]uint32, lInd)

	for n := uint32(0); n < lT; n++ {
		p = table[n]
		if (p >> 24) == 0xfe {
			status = errGenUfindIntTable - 21
			if i >= lInd {
				return status
			}
			next[n] = lT + i
			ind[i] = lT + i
			next[lT+i] = n
			i++
		} else {
			p &= mask
			if (table[p] >> 24) != 0xfe {
				return errGenUfindIntTable - 23
			}
			j = next[p] - lT
			if j >= i {
				return errGenUfindIntTable - 24
			}
			last = ind[j]
			if next[last] != p {
				return errGenUfindIntTable - 25
			}
			ind[j] = n
			next[last] = n
			next[n] = p
		}
	}

	lInd = i

	n := uint32(0)
	for i = 0; i < lInd; i++ {
		lastN = n
		last = ind[i]
		fst = next[last]
		mapOut[n] = fst
		n++
		table[fst] = lastN | 0xfe000000
		p = next[lT+i]
		for p != fst {
			mapOut[n] = p
			n++
			p = next[p]
		}
		writeLengthInfo(mapOut[lastN:], n-lastN)
	}

	if n != lT {
		return errGenUfindIntTable - 26
	}
	return int32(lInd)
}

// computeSchreierVector computes a Schreier vector for
// the group encoded in the orbit array referred by s
// (which must have status 0). It writes the vector into
// s.pT and uses s.pO as scratch (the queue / forest).
// Returns the number of orbits on success, negative on
// failure. Mirrors compute_schreier_vector.
//
// The bitmap is aliased onto s.pT (the same backing
// array as the C code reuses p_t as the bitmap during
// the search, before overwriting it with the Schreier
// vector at the end).
func computeSchreierVector(s *lin2Type) int32 {
	nSize := uint32(1) << s.n
	nG := s.nG
	nOrbits := uint32(0)
	current := uint32(0)

	if s.status != 0 {
		return errGenUfindState
	}

	// The bitmap occupies (nSize>>6)+1 uint64 words,
	// aliased onto s.pT. We use a standalone []uint64
	// and copy the Schreier vector into s.pT at the end;
	// this matches the observable result of the C code,
	// where p_t holds the Schreier vector afterwards.
	bitmap := make([]uint64, (nSize>>6)+1)
	for i := range bitmap {
		bitmap[i] = ^uint64(0)
	}

	g := make([]uint64, nG*0x300)
	for i := uint32(0); i < nG; i++ {
		store64Gen(g[0x300*i:], s.n, lin2Generator(s, 2*i), lin2Generator(s, 2*i+1))
	}

	pStart := uint32(0) // write/read cursor head of forest into s.pO
	pEnd := uint32(0)   // tail of forest into s.pO
	pOverflow := nSize

	for {
		current = findNextBitSet(bitmap, current)
		if current >= nSize {
			break
		}
		nOrbits++
		if pStart >= pOverflow {
			return errGenUfindIntLin2 - 25
		}
		s.pO[pStart] = current | 0xfe000000
		pEnd = pStart + 1
		bitmap[current>>6] ^= uint64(1) << (current & 0x3f)
		current++

		for pStart < pEnd {
			data := s.pO[pStart]
			pStart++
			d0 := data & 0xff
			d1 := ((data >> 8) & 0xff) + 0x100
			d2 := ((data >> 16) & 0xff) + 0x200
			pg := uint32(0)
			for i := uint32(0); i < nG; i++ {
				v64 := g[pg+d0] ^ g[pg+d1] ^ g[pg+d2]
				img0 := v64 & 0xffffffff
				img1 := v64 >> 32
				mask0 := uint64(1) << (img0 & 0x3f)
				mask1 := uint64(1) << (img1 & 0x3f)
				pg += 0x300
				if bitmap[img0>>6]&mask0 != 0 {
					bitmap[img0>>6] ^= mask0
					if pEnd >= pOverflow {
						return errGenUfindIntLin2 - 25
					}
					s.pO[pEnd] = uint32(img0) | (i << 25) | 0x01000000
					pEnd++
				}
				if bitmap[img1>>6]&mask1 != 0 {
					bitmap[img1>>6] ^= mask1
					if pEnd >= pOverflow {
						return errGenUfindIntLin2 - 25
					}
					s.pO[pEnd] = uint32(img1) | (i << 25)
					pEnd++
				}
			}
		}
	}

	// Convert the forest in s.pO into the Schreier
	// vector in s.pT.
	rep := uint32(0)
	for i := uint32(0); i < nSize; i++ {
		v := s.pO[i]
		rg := v & 0xff000000
		idx := v & 0xffffff
		if rg == 0xfe000000 {
			rep = idx
		}
		s.pT[idx] = rg | rep
	}
	return int32(nOrbits)
}

// magicContent returns a hash over the header of the
// orbit array a. Mirrors magic_content.
func magicContent(a []uint32) uint32 {
	s := uint32(lin2Magic)
	for i := 0; i < lin2LenHeader; i++ {
		s = s*lin2AMul + a[i]
	}
	return s
}

// finalizeInitialization upgrades the status of the
// orbit array a to 2 (computing the Schreier vector and
// the orbit partition), stores header information into
// s, and writes the checksum trailer. Returns the
// status (a negative value indicates an error). Mirrors
// finalize_initalization.
func finalizeInitialization(a []uint32, s *lin2Type) int32 {
	status := loadLin2Info(a, s)
	if status == 2 || status == lin2Compressed || status < 0 {
		return status
	}
	if status != 0 {
		return errGenUfindState
	}
	status = computeSchreierVector(s)
	if status < 0 {
		return lin2Error(a, status)
	}
	s.nOrbits = uint32(status)
	status = computePartition(s.pT, s.n, s.pO, s.nOrbits)
	if status < 0 {
		return lin2Error(a, status)
	}
	s.status = 2
	s.nMaxG = s.nG
	status = storeLin2Info(s, a)
	if status < 0 {
		lin2Error(a, status)
	}
	aLength := lin2GeneratorSize(s.n, s.nG) + lin2LenHeader + (2 << s.n) + 2
	a[aLength-2] = magicContent(a)
	var aSum uint32
	for i := uint32(0); i < aLength-1; i++ {
		aSum += a[i]
	}
	a[aLength-1] = 0 - aSum
	return status
}

// computeGroupOrbitNew computes the orbit of a[0] and
// stores it in the slice a (length lenA). It is a
// simplified compute_schreier_vector for compressed
// arrays. Returns the orbit length on success, negative
// on failure. Mirrors compute_group_orbit_new.
func computeGroupOrbitNew(s *lin2Type, a []uint32, lenA uint32) int32 {
	nSize := uint32(1) << s.n
	nG := s.nG
	bitmapSize := (nSize >> 6) + 1

	if s.status < 0 {
		return errGenUfindState
	}
	if lenA == 0 {
		return errGenUfindIntLin2 - 25
	}
	bitmap := make([]uint64, bitmapSize)
	for i := range bitmap {
		bitmap[i] = ^uint64(0)
	}
	g := make([]uint64, nG*0x300)
	for i := uint32(0); i < nG; i++ {
		store64Gen(g[0x300*i:], s.n, lin2Generator(s, 2*i), lin2Generator(s, 2*i+1))
	}
	bitmap[a[0]>>6] ^= uint64(1) << (a[0] & 0x3f)

	pStart := uint32(0)
	pEnd := uint32(1)
	pOverflow := lenA
	for pStart < pEnd {
		data := a[pStart]
		pStart++
		d0 := data & 0xff
		d1 := ((data >> 8) & 0xff) + 0x100
		d2 := ((data >> 16) & 0xff) + 0x200
		pg := uint32(0)
		for i := uint32(0); i < nG; i++ {
			v64 := g[pg+d0] ^ g[pg+d1] ^ g[pg+d2]
			img0 := v64 & 0xffffffff
			mask0 := uint64(1) << (img0 & 0x3f)
			pg += 0x300
			if bitmap[img0>>6]&mask0 != 0 {
				bitmap[img0>>6] ^= mask0
				if pEnd >= pOverflow {
					return errGenUfindIntLin2 - 25
				}
				a[pEnd] = uint32(img0) | (i << 25) | 0x01000000
				pEnd++
			}
		}
	}
	return int32(pEnd - pStart)
}

// bitvector32Bsearch performs a binary search in the
// sorted slice a of n uint32s. It returns the lowest
// index i with v <= a[i], or n-1 if v > a[n-1], or 0
// if n == 0. Mirrors bitvector32_bsearch.
func bitvector32Bsearch(a []uint32, n, v uint32) uint32 {
	lo := uint32(0)
	for n > 1 {
		mid := n >> 1
		if v > a[lo+mid-1] {
			lo += mid
			mid = n - mid
		}
		n = mid
	}
	return lo
}

// compressedLin2MapV is equivalent to lin2 map_v when
// the orbit array is compressed. Mirrors
// compressed_lin2_map_v.
func compressedLin2MapV(a []uint32, v uint32, b []uint8, lB uint32) int32 {
	var s lin2Type
	status := loadLin2Info(a, &s)
	if status < 0 {
		return status
	}
	if status != lin2Compressed {
		return errGenUfindState
	}
	mask := uint32(1)<<s.n - 1
	lBStart := lB
	bIdx := uint32(0)
	for {
		v &= mask
		x := s.pT[bitvector32Bsearch(s.pT, s.nVectors, v<<8)]
		g := x & 0xff
		x >>= 8
		if x^v != 0 || g > 0xfe {
			return errGenUfindEntryUF
		}
		if g == 0xfe {
			return int32(lBStart - lB)
		}
		if lB == 0 {
			return errGenUfindOutShort
		}
		lB--
		b[bIdx] = uint8(g)
		bIdx++
		v = vmatmulAff(v, lin2Generator(&s, g), s.n)
	}
}

// compressedLin2RepV is equivalent to lin2 rep_v when
// the orbit array is compressed. Mirrors
// compressed_lin2_rep_v.
func compressedLin2RepV(a []uint32, v uint32) int32 {
	var s lin2Type
	status := loadLin2Info(a, &s)
	if status < 0 {
		return status
	}
	if status != lin2Compressed {
		return errGenUfindState
	}
	mask := uint32(1)<<s.n - 1
	lB := s.nVectors
	for {
		lB--
		if lB == 0 {
			break
		}
		v &= mask
		x := s.pT[bitvector32Bsearch(s.pT, s.nVectors, v<<8)]
		g := x & 0xff
		x >>= 8
		if x^v != 0 || g > 0xfe {
			return errGenUfindEntryUF
		}
		if g == 0xfe {
			return int32(v)
		}
		v = vmatmulAff(v, lin2Generator(&s, g), s.n)
	}
	return errGenUfindOutShort
}

// bitmatrix64Inv inverts the bit matrix m (i rows, i
// columns, i <= 32) in place. Returns 0 on success and
// a negative value if m is not invertible or i > 32.
// Ported from bitmatrix64.ske bitmatrix64_inv and its
// helpers.
func bitmatrix64Inv(m []uint64, i uint32) int32 {
	if i > 32 {
		return -1 // ERR_QSTATE12_TOOLARGE
	}
	if i == 0 {
		return 0
	}
	bitmatrix64MaskRows(m, i, (uint64(1)<<i)-1)
	bitmatrix64AddDiag(m, i, i)
	bitmatrix64EchelonL(m, i, 0, 2*i)
	if m[i-1]&((uint64(1)<<i)-1) == 0 {
		return -1 // ERR_QSTATE12_MATRIX_INV (not invertible)
	}
	if bitmatrix64RotBits(m, i, int32(i), 2*i, 0) < 0 {
		return -1
	}
	bitmatrix64MaskRows(m, i, (uint64(1)<<i)-1)
	return 0
}

// bitmatrix64MaskRows replaces each of the i rows of m
// by m[k] & mask. Mirrors bitmatrix64_mask_rows.
func bitmatrix64MaskRows(m []uint64, i uint32, mask uint64) {
	for k := uint32(0); k < i; k++ {
		m[k] &= mask
	}
}

// bitmatrix64AddDiag adds one to all entries m[k, j+k]
// for 0 <= k < i. Mirrors bitmatrix64_add_diag.
func bitmatrix64AddDiag(m []uint64, i, j uint32) {
	if j >= 64 {
		return
	}
	mask := uint64(1) << j
	for k := uint32(0); k < i; k++ {
		m[k] ^= mask
		mask <<= 1
	}
}

// bitmatrix64EchelonL converts the i-row bit matrix m
// to reduced row echelon form, pivoting over columns
// j0 .. j0+n-1 with the leading bit being the least
// significant. Returns the number of pivoted rows.
// Mirrors bitmatrix64_echelon_l.
func bitmatrix64EchelonL(m []uint64, i, j0, n uint32) uint32 {
	if j0 >= 64 || i == 0 || n == 0 {
		return 0
	}
	if j0+n > 64 {
		n = 64 - j0
	}
	rowPos := int32(0)
	for col := int32(j0); col < int32(j0+n); col++ {
		colMask := uint64(1) << uint32(col)
		for k1 := int32(i) - 1; k1 >= rowPos; k1-- {
			if m[k1]&colMask != 0 {
				v := m[k1]
				for k2 := k1 - 1; k2 >= 0; k2-- {
					m[k2] ^= (0 - ((m[k2] >> uint32(col)) & 1)) & v
				}
				m[k1] = m[rowPos]
				m[rowPos] = v
				rowPos++
				break
			}
		}
	}
	return uint32(rowPos)
}

// bitmatrix64RotBits rotates columns of the i-row bit
// matrix m: for n0 <= j < n0+nrot, column j maps to
// column n0 + (j+rot)%nrot. Returns 0 on success and a
// negative value if a column index >= 64 is involved.
// Mirrors bitmatrix64_rot_bits.
func bitmatrix64RotBits(m []uint64, i uint32, rot int32, nrot, n0 uint32) int32 {
	if nrot+n0 > 64 {
		return -1 // ERR_QSTATE12_QUBIT_INDEX
	}
	if nrot < 2 {
		return 0
	}
	if rot < 0 {
		rot += int32(nrot)*(-rot/int32(nrot)) + int32(nrot)
	}
	rot %= int32(nrot)
	if rot == 0 {
		return 0
	}
	nmax := nrot + n0
	maskL := uint64(1) << (nmax - uint32(rot))
	var maskH uint64
	if nmax < 64 {
		maskH = uint64(1) << nmax
	}
	maskH -= maskL
	maskL -= uint64(1) << n0
	mask := ^(maskL | maskH)
	sh := nrot - uint32(rot)
	for k := uint32(0); k < i; k++ {
		m[k] = (m[k] & mask) | ((m[k] & maskL) << uint32(rot)) | ((m[k] & maskH) >> sh)
	}
	return 0
}

/*************************************************************************
*** Exported wrappers
*************************************************************************/

// UFindLin2MulAffine transforms a vector v with the
// affine mapping v -> v*A + b on GF(2)^n. Row i of A is
// m[i], and b is m[n]. It returns the bit vector
// v*A + b. Mirrors gen_ufind_lin2_mul_affine.
func UFindLin2MulAffine(v uint32, m []uint32, n uint32) uint32 {
	return vmatmulAff(v, m, n)
}

// UFindLin2Size returns the number of uint32s required
// for an orbit array for a group acting on GF(2)^n with
// up to k generators. It panics if n is 0 or greater
// than 24, or if k exceeds 127. Mirrors
// gen_ufind_lin2_size.
func UFindLin2Size(n, k uint32) int32 {
	status := lin2Size(n, k)
	if status < 0 {
		panic(lin2Panic("UFindLin2Size", status))
	}
	return status
}

// lin2Size is the comma-error internal form of
// gen_ufind_lin2_size.
func lin2Size(n, k uint32) int32 {
	if n == 0 || n > lin2MaxN {
		return errGenUfindLin2Dim
	}
	if k > lin2MaxNG {
		return errGenUfindLin2Gen
	}
	return int32(lin2LenHeader + (2 << n) + lin2GeneratorSize(n, k) + 2)
}

// UFindLin2Init initializes the orbit array a (of
// length lA) for a group acting on GF(2)^n with up to
// nG generators. The required length can be obtained
// from UFindLin2Size(n, nG). It panics on error, e.g.
// if a is too short, n is out of range, or nG exceeds
// 127. Mirrors gen_ufind_lin2_init.
func UFindLin2Init(a []uint32, lA, n, nG uint32) int32 {
	status := lin2Init(a, lA, n, nG)
	if status < 0 {
		panic(lin2Panic("UFindLin2Init", status))
	}
	return status
}

func lin2Init(a []uint32, lA, n, nG uint32) int32 {
	var s lin2Type
	lAExpected := lin2Size(n, nG)
	status := lAExpected
	if status < 0 {
		return lin2Error(a, status)
	}
	status = checkOutBuf32(a, lA, uint32(lAExpected))
	if status < 0 {
		return lin2Error(a, status)
	}
	s.status = 0
	s.n = n
	s.nMaxG = nG
	s.nG = 0
	s.nOrbits = 0
	s.nVectors = uint32(1) << n
	storeLin2Info(&s, a)
	status = loadLin2Info(a, &s)
	return lin2Error(a, status)
}

// UFindLin2Dim returns the dimension n of the vector
// space GF(2)^n stored in the orbit array a. It panics
// on error. Mirrors gen_ufind_lin2_dim.
func UFindLin2Dim(a []uint32) int32 {
	var s lin2Type
	status := loadLin2Info(a, &s)
	if status < 0 {
		panic(lin2Panic("UFindLin2Dim", status))
	}
	return int32(s.n)
}

// UFindLin2NGen returns the number of generators of the
// group stored in the orbit array a. It panics on
// error. Mirrors gen_ufind_lin2_n_gen.
func UFindLin2NGen(a []uint32) int32 {
	var s lin2Type
	status := loadLin2Info(a, &s)
	if status < 0 {
		panic(lin2Panic("UFindLin2NGen", status))
	}
	return int32(s.nG)
}

// UFindLin2NMaxGen returns the maximum number of
// generators that can be stored in the orbit array a.
// It panics on error. Mirrors gen_ufind_lin2_n_max_gen.
func UFindLin2NMaxGen(a []uint32) int32 {
	var s lin2Type
	status := loadLin2Info(a, &s)
	if status < 0 {
		panic(lin2Panic("UFindLin2NMaxGen", status))
	}
	return int32(s.nMaxG)
}

// UFindLin2Pad increases the maximum number of
// generators that may be stored in the orbit array a
// (of allocated length lenA) to nMaxG, returning the
// new maximum. It panics on error, e.g. if a is too
// short, the array has already been finalized, or nMaxG
// exceeds 127. Mirrors gen_ufind_lin2_pad.
func UFindLin2Pad(a []uint32, lenA, nMaxG uint32) int32 {
	var s lin2Type
	status := loadLin2Info(a, &s)
	if status < 0 {
		panic(lin2Panic("UFindLin2Pad", status))
	}
	if status >= 2 {
		panic(lin2Panic("UFindLin2Pad", errGenUfindState))
	}
	if nMaxG > lin2MaxNG {
		panic(lin2Panic("UFindLin2Pad", errGenUfindLin2Gen))
	}
	if nMaxG < s.nMaxG {
		nMaxG = s.nMaxG
	}
	status = lin2Size(s.n, nMaxG)
	if status < 0 {
		panic(lin2Panic("UFindLin2Pad", status))
	}
	if lenA < uint32(status) {
		panic(lin2Panic("UFindLin2Pad", errGenUfindOutShort))
	}
	s.nMaxG = nMaxG
	storeLin2Info(&s, a)
	return int32(nMaxG)
}

// UFindLin2Gen reads the i-th generator (i even) or its
// inverse (i odd) of the group stored in the orbit
// array a into the slice g (length lG). The generator
// is returned as an n x n bit matrix; if the affine
// part b is nonzero it is stored in g[n] (requiring
// lG > n). It returns n on success and panics on error,
// e.g. if i is out of range or g is too short. Mirrors
// gen_ufind_lin2_gen.
func UFindLin2Gen(a []uint32, i uint32, g []uint32, lG uint32) int32 {
	var s lin2Type
	status := loadLin2Info(a, &s)
	if status < 0 {
		panic(lin2Panic("UFindLin2Gen", status))
	}
	if i >= 2*s.nG {
		panic(lin2Panic("UFindLin2Gen", errGenUfindInLarge))
	}
	pGen := lin2Generator(&s, i)
	lenAff := s.n
	if pGen[s.n] != 0 {
		lenAff++
	}
	if checkOutBuf32(g, lG, lenAff) != 0 {
		panic(lin2Panic("UFindLin2Gen", errGenUfindOutShort))
	}
	copy(g[:lenAff], pGen[:lenAff])
	return int32(s.n)
}

// UFindLin2Add adds a generator g (an n x n bit matrix
// in the first n entries; an affine offset b in g[n] if
// lG > n) to the group stored in the orbit array a. It
// returns 0 on success and panics on error, e.g. if the
// array is not in the initial state, the generator
// limit is exhausted, or the generator is not
// invertible. Mirrors gen_ufind_lin2_add.
func UFindLin2Add(a []uint32, g []uint32, lG uint32) int32 {
	var s lin2Type
	status := loadLin2Info(a, &s)
	if status != 0 {
		if status < 0 {
			panic(lin2Panic("UFindLin2Add", status))
		}
		panic(lin2Panic("UFindLin2Add", errGenUfindState))
	}
	mask := uint32(1)<<s.n - 1
	if checkOutBuf32(g, lG, s.n) < 0 {
		a[0] = u32(errGenUfindOutShort)
		panic(lin2Panic("UFindLin2Add", errGenUfindOutShort))
	}
	affine := lG > s.n
	if s.nG >= s.nMaxG {
		a[0] = u32(errGenUfindLin2Gen)
		panic(lin2Panic("UFindLin2Add", errGenUfindLin2Gen))
	}
	pGout := lin2Generator(&s, 2*s.nG)
	for j := uint32(0); j < s.n; j++ {
		pGout[j] = g[j] & mask
	}
	if affine {
		pGout[s.n] = g[s.n] & mask
	} else {
		pGout[s.n] = 0
	}
	pGoutInv := lin2Generator(&s, 2*s.nG+1)
	if matInverseAff(pGout, s.n, pGoutInv) != 0 {
		a[0] = u32(errGenUfindInverse)
		panic(lin2Panic("UFindLin2Add", errGenUfindInverse))
	}
	s.nG++
	storeLin2Info(&s, a)
	return 0
}

// UFindLin2TransformV transforms the bit vector v by
// the group element given as a word b (length lB) of
// generator indices, where entry i corresponds to the
// generator returned by UFindLin2Gen(a, i, ...). The
// neutral element 0xfe is skipped. It returns the
// transformed vector and panics on error. Mirrors
// gen_ufind_lin2_transform_v.
func UFindLin2TransformV(a []uint32, v uint32, b []uint8, lB uint32) int32 {
	var s lin2Type
	status := loadLin2Info(a, &s)
	if status < 0 {
		panic(lin2Panic("UFindLin2TransformV", status))
	}
	v &= uint32(1)<<s.n - 1
	for i := uint32(0); i < lB; i++ {
		if uint32(b[i]) >= 2*s.nG {
			if b[i] == 0xfe {
				continue
			}
			panic(lin2Panic("UFindLin2TransformV", errGenUfindIntLin2-36))
		}
		v = vmatmulAff(v, lin2Generator(&s, uint32(b[i])), s.n)
	}
	return int32(v)
}

// UFindLin2CompressedSize returns the number of uint32s
// required for a compressed orbit array holding the
// orbits of the vectors in o (length lO), extracted
// from the orbit array a. It panics on error. Mirrors
// gen_ufind_lin2_compressed_size.
func UFindLin2CompressedSize(a []uint32, o []uint32, lO uint32) int32 {
	var s lin2Type
	status := finalizeInitialization(a, &s)
	if status != 2 {
		if status < 0 {
			panic(lin2Panic("UFindLin2CompressedSize", status))
		}
		panic(lin2Panic("UFindLin2CompressedSize", errGenUfindState))
	}
	bitmapSize := ((uint32(1) << s.n) >> 6) + 1
	bitmap := make([]uint64, bitmapSize)
	setBitmap(bitmap, uint32(1)<<s.n)
	mask := uint32(1)<<s.n - 1
	nEntries := uint32(0)
	nOrbits := uint32(0)

	for i := uint32(0); i < lO; i++ {
		v := o[i] & mask
		w := s.pT[v]
		if (w >> 24) != 0xfe {
			v = s.pT[v] & mask
			w = s.pT[v]
		}
		if getBitmap(bitmap, v) != 0 {
			continue
		}
		setBitmap(bitmap, v)
		w &= mask
		lOrbit := readLengthInfo(s.pO[w:])
		if lOrbit < 0 {
			panic(lin2Panic("UFindLin2CompressedSize", lOrbit))
		}
		nOrbits++
		nEntries += uint32(lOrbit)
	}
	return int32(lin2LenHeader + nEntries + 2*nOrbits + lin2GeneratorSize(s.n, s.nG) + 2)
}

// getBitmap reads bit j of the 64-bit-word bitmap.
// Mirrors the get_bitmap macro.
func getBitmap(bitmap []uint64, j uint32) uint32 {
	return uint32((bitmap[j>>6] >> (j & 63)) & 1)
}

// setBitmap sets bit j of the 64-bit-word bitmap.
// Mirrors the set_bitmap macro.
func setBitmap(bitmap []uint64, j uint32) {
	bitmap[j>>6] |= uint64(1) << (j & 63)
}

// makeCompressed builds the compressed orbit array c
// (length lC) from the orbit array a using the bitmap
// of selected vectors. nEntries and nOrbits are the
// counts of bit vectors and orbits to be stored. It
// returns the length of c, or a negative value on
// error. Mirrors make_compressed.
func makeCompressed(a []uint32, bitmap []uint64, nEntries, nOrbits uint32, c []uint32, lC uint32) int32 {
	var s, sc lin2Type
	status := loadLin2Info(a, &s)
	if status != 2 {
		if status < 0 {
			return status
		}
		return errGenUfindState
	}
	vmax := uint32(1) << s.n
	mask := vmax - 1

	sc = s
	sc.status = lin2Compressed
	sc.nVectors = nEntries
	sc.nOrbits = nOrbits
	cSize := lin2LenHeader + sc.nVectors + 2*sc.nOrbits + lin2GeneratorSize(sc.n, sc.nG) + 2
	if lC < cSize {
		return errGenUfindOutShort
	}
	sc.pT = c[lin2LenHeader:]
	sc.pO = sc.pT[sc.nVectors:]
	sc.pG = sc.pO[2*sc.nOrbits:]
	genSize := lin2GeneratorSize(s.n, s.nG)
	copy(sc.pG[:genSize], s.pG[:genSize])

	entriesFound := uint32(0)
	orbitsFound := uint32(0)
	v := uint32(0)
	for {
		v = findNextBitSet(bitmap, v)
		if v >= vmax {
			break
		}
		w := s.pT[v]
		g := w >> 24
		if g == 0xfe {
			lenO := readLengthInfo(s.pO[w&mask:])
			sc.pO[orbitsFound] = v
			sc.pO[orbitsFound+nOrbits] = uint32(lenO)
			orbitsFound++
		}
		sc.pT[entriesFound] = (v << 8) + g
		entriesFound++
		v++
	}
	if orbitsFound != nOrbits {
		return errGenUfindIntLin2 - 64
	}
	if entriesFound != nEntries {
		return errGenUfindIntLin2 - 65
	}

	c[0] = 0
	storeLin2Info(&sc, c)
	c[cSize-2] = magicContent(c)
	var cSum uint32
	for i := uint32(0); i < cSize-1; i++ {
		cSum += c[i]
	}
	c[cSize-1] = 0 - cSum
	return int32(cSize)
}

// UFindLin2Compress extracts the orbits of the vectors
// in o (length lO) from the orbit array a into the
// compressed orbit array c (length lC). The required
// length of c can be obtained from
// UFindLin2CompressedSize. It returns the actual length
// of c and panics on error. Mirrors
// gen_ufind_lin2_compress.
func UFindLin2Compress(a []uint32, o []uint32, lO uint32, c []uint32, lC uint32) int32 {
	status := lin2Compress(a, o, lO, c, lC)
	if status < 0 {
		panic(lin2Panic("UFindLin2Compress", status))
	}
	return status
}

func lin2Compress(a []uint32, o []uint32, lO uint32, c []uint32, lC uint32) int32 {
	var s lin2Type
	status := finalizeInitialization(a, &s)
	if status != 2 {
		if status < 0 {
			return status
		}
		return errGenUfindState
	}
	if c == nil {
		return errGenUfindOutShort
	}
	c[0] = u32(errGenUfindIntLin2 - 61)
	bitmapSize := ((uint32(1) << s.n) >> 6) + 1
	bitmap := make([]uint64, bitmapSize)
	setBitmap(bitmap, uint32(1)<<s.n)
	mask := uint32(1)<<s.n - 1
	nEntries := uint32(0)
	nOrbits := uint32(0)

	for i := uint32(0); i < lO; i++ {
		v := o[i] & mask
		w := s.pT[v]
		if (w >> 24) != 0xfe {
			v = s.pT[v] & mask
			w = s.pT[v]
			if (w >> 24) != 0xfe {
				status = errGenUfindIntLin2 - 62
				c[0] = uint32(status)
				return status
			}
		}
		if getBitmap(bitmap, v) != 0 {
			continue
		}
		w &= mask
		lOrbit := readLengthInfo(s.pO[w:])
		if lOrbit < 0 {
			c[0] = uint32(lOrbit)
			return lOrbit
		}
		nOrbits++
		nEntries += uint32(lOrbit)
		if (s.pO[w] & mask) != v {
			status = errGenUfindIntLin2 - 63
			c[0] = uint32(status)
			return status
		}
		for j := w; j < w+uint32(lOrbit); j++ {
			setBitmap(bitmap, s.pO[j]&mask)
		}
	}
	status = makeCompressed(a, bitmap, nEntries, nOrbits, c, lC)
	if status < 0 {
		c[0] = uint32(status)
	}
	return status
}

// UFindLin2NOrbits returns the number of orbits on the
// vector space under the action of the group stored in
// the orbit array a. It triggers finalization if needed
// and panics on error. Mirrors gen_ufind_lin2_n_orbits.
func UFindLin2NOrbits(a []uint32) int32 {
	var s lin2Type
	status := finalizeInitialization(a, &s)
	if status < 0 {
		panic(lin2Panic("UFindLin2NOrbits", status))
	}
	return int32(s.nOrbits)
}

// UFindLin2RepV returns a representative of the orbit of
// the bit vector v under the action of the group stored
// in the orbit array a. It triggers finalization if
// needed and panics on error. Mirrors
// gen_ufind_lin2_rep_v.
func UFindLin2RepV(a []uint32, v uint32) int32 {
	status := lin2RepV(a, v)
	if status < 0 {
		panic(lin2Panic("UFindLin2RepV", status))
	}
	return status
}

func lin2RepV(a []uint32, v uint32) int32 {
	var s lin2Type
	status := finalizeInitialization(a, &s)
	if status < 0 {
		return status
	}
	if status == lin2Compressed {
		return compressedLin2RepV(a, v)
	}
	mask := uint32(1)<<s.n - 1
	v &= mask
	entry := s.pT[v]
	if ((entry >> 24) & 0xff) == 0xfe {
		return int32(v)
	}
	return int32(entry & mask)
}

// UFindLin2LenOrbitV returns the length of the orbit of
// the bit vector v under the action of the group stored
// in the orbit array a. It triggers finalization if
// needed and panics on error. Mirrors
// gen_ufind_lin2_len_orbit_v.
func UFindLin2LenOrbitV(a []uint32, v uint32) int32 {
	var s lin2Type
	status := finalizeInitialization(a, &s)
	if status < 0 {
		panic(lin2Panic("UFindLin2LenOrbitV", status))
	}
	mask := uint32(1)<<s.n - 1
	v &= mask
	if status == lin2Compressed {
		rv := compressedLin2RepV(a, v)
		if rv < 0 {
			panic(lin2Panic("UFindLin2LenOrbitV", rv))
		}
		v = uint32(rv)
		indexO := bitvector32Bsearch(s.pO, s.nOrbits, v)
		if v != s.pO[indexO] {
			panic(lin2Panic("UFindLin2LenOrbitV", errGenUfindIntLin2-35))
		}
		return int32(s.pO[s.nOrbits+indexO])
	}
	rep := lin2RepV(a, v)
	if rep < 0 {
		panic(lin2Panic("UFindLin2LenOrbitV", rep))
	}
	indexO := s.pT[rep] & mask
	d := readLengthInfo(s.pO[indexO:])
	if d < 0 {
		panic(lin2Panic("UFindLin2LenOrbitV", d))
	}
	return d
}

// UFindLin2OrbitV writes the orbit of the bit vector v
// under the action of the group stored in the orbit
// array a into the slice r (length lR), returning the
// orbit length. The required length can be obtained
// from UFindLin2LenOrbitV. It panics on error, e.g. if
// r is too short. Mirrors gen_ufind_lin2_orbit_v.
func UFindLin2OrbitV(a []uint32, v uint32, r []uint32, lR uint32) int32 {
	status := lin2OrbitV(a, v, r, lR)
	if status < 0 {
		panic(lin2Panic("UFindLin2OrbitV", status))
	}
	return status
}

func lin2OrbitV(a []uint32, v uint32, r []uint32, lR uint32) int32 {
	var s lin2Type
	status := finalizeInitialization(a, &s)
	if status < 0 {
		return status
	}
	mask := uint32(1)<<s.n - 1
	if status == lin2Compressed {
		if lR == 0 {
			return errGenUfindOutShort
		}
		r[0] = v & mask
		return computeGroupOrbitNew(&s, r, lR)
	}
	rep := lin2RepV(a, v)
	if rep < 0 {
		return rep
	}
	indexO := s.pT[rep] & mask
	pO := s.pO[indexO:]
	length := readLengthInfo(s.pO[indexO:])
	if length < 0 {
		return length
	}
	if checkOutBuf32(r, lR, uint32(length)) != 0 {
		return errGenUfindOutShort
	}
	for i := uint32(0); i < uint32(length); i++ {
		r[i] = pO[i] & mask
	}
	return length
}

// UFindLin2Representatives writes a representative of
// each orbit stored in the orbit array a into the slice
// r (length lR), returning the number of orbits. The
// number of orbits can be obtained from
// UFindLin2NOrbits. It panics on error, e.g. if r is
// too short. Mirrors gen_ufind_lin2_representatives.
func UFindLin2Representatives(a []uint32, r []uint32, lR uint32) int32 {
	status := lin2Representatives(a, r, lR)
	if status < 0 {
		panic(lin2Panic("UFindLin2Representatives", status))
	}
	return status
}

func lin2Representatives(a []uint32, r []uint32, lR uint32) int32 {
	var s lin2Type
	status := finalizeInitialization(a, &s)
	if status < 0 {
		return status
	}
	if status == lin2Compressed {
		if s.nOrbits > lR {
			return errGenUfindOutShort
		}
		copy(r[:s.nOrbits], s.pO[:s.nOrbits])
		return int32(s.nOrbits)
	}
	mask := uint32(1)<<s.n - 1
	indexO := uint32(0)
	lR1 := lR
	rIdx := uint32(0)
	for indexO < (uint32(1) << s.n) {
		d := readLengthInfo(s.pO[indexO:])
		if d < 0 {
			return -d
		}
		if lR1 == 0 {
			return errGenUfindOutShort
		}
		lR1--
		r[rIdx] = s.pO[indexO] & mask
		rIdx++
		indexO += uint32(d)
	}
	return int32(lR - lR1)
}

// UFindLin2OrbitLengths writes the length of each orbit
// stored in the orbit array a into the slice r (length
// lR), in the same order as UFindLin2Representatives,
// returning the number of orbits. It panics on error,
// e.g. if r is too short. Mirrors
// gen_ufind_lin2_orbit_lengths.
func UFindLin2OrbitLengths(a []uint32, r []uint32, lR uint32) int32 {
	status := lin2OrbitLengths(a, r, lR)
	if status < 0 {
		panic(lin2Panic("UFindLin2OrbitLengths", status))
	}
	return status
}

func lin2OrbitLengths(a []uint32, r []uint32, lR uint32) int32 {
	var s lin2Type
	status := finalizeInitialization(a, &s)
	if status < 0 {
		return status
	}
	if status == lin2Compressed {
		if s.nOrbits > lR {
			return errGenUfindOutShort
		}
		copy(r[:s.nOrbits], s.pO[s.nOrbits:2*s.nOrbits])
		return int32(s.nOrbits)
	}
	indexO := uint32(0)
	lR1 := lR
	rIdx := uint32(0)
	for indexO < (uint32(1) << s.n) {
		d := readLengthInfo(s.pO[indexO:])
		if d < 0 {
			return -d
		}
		if lR1 == 0 {
			return errGenUfindOutShort
		}
		lR1--
		r[rIdx] = uint32(d)
		rIdx++
		indexO += uint32(d)
	}
	return int32(lR - lR1)
}

// UFindLin2MapVGen returns the Schreier vector entry for
// the bit vector v in the orbit array a: an index i <
// 0xfe refers to the generator UFindLin2Gen(a, i, ...);
// 0xfe means v is its orbit representative; 0xff means
// the Schreier vector for v has not been computed. It
// panics on a negative error. Mirrors
// gen_ufind_lin2_map_v_gen.
func UFindLin2MapVGen(a []uint32, v uint32) int32 {
	var s lin2Type
	status := finalizeInitialization(a, &s)
	if status < 0 {
		panic(lin2Panic("UFindLin2MapVGen", status))
	}
	if status == lin2Compressed {
		x := bitvector32Bsearch(s.pO, s.nVectors, v<<8)
		g := x & 0xff
		x >>= 8
		if x^v != 0 || g > 0xfe {
			return 0xff
		}
		return int32(g)
	}
	mask := uint32(1)<<s.n - 1
	return int32((s.pT[v&mask] >> 24) & 0xff)
}

// UFindLin2MapV computes a group element g mapping the
// bit vector v to the representative of its orbit, and
// stores g as a word of generator indices in the slice
// b (length lB), where entry i corresponds to the
// generator UFindLin2Gen(a, i, ...). It returns the
// word length and panics on error. Mirrors
// gen_ufind_lin2_map_v.
func UFindLin2MapV(a []uint32, v uint32, b []uint8, lB uint32) int32 {
	status := lin2MapV(a, v, b, lB)
	if status < 0 {
		panic(lin2Panic("UFindLin2MapV", status))
	}
	return status
}

func lin2MapV(a []uint32, v uint32, b []uint8, lB uint32) int32 {
	var s lin2Type
	status := finalizeInitialization(a, &s)
	if status < 0 {
		return status
	}
	if status == lin2Compressed {
		return compressedLin2MapV(a, v, b, lB)
	}
	mask := uint32(1)<<s.n - 1
	v &= mask
	entry := s.pT[v]
	var w uint32
	if ((entry >> 24) & 0xff) == 0xfe {
		w = v
	} else {
		w = entry & mask
	}
	lB1 := lB
	bIdx := uint32(0)
	for {
		gen := (entry >> 24) & 0xff
		if gen == 0xfe {
			return int32(lB - lB1)
		}
		if (entry & mask) != w {
			return errGenUfindIntLin2 - 31
		}
		if lB1 == 0 {
			return errGenUfindOutShort
		}
		lB1--
		b[bIdx] = uint8(gen)
		bIdx++
		if gen >= 2*s.nG {
			return errGenUfindIntLin2 - 32
		}
		v = vmatmulAff(v, lin2Generator(&s, gen), s.n)
		entry = s.pT[v]
	}
}

// UFindLin2Finalize computes and stores all derivable
// orbit information (Schreier vector, orbit partition,
// checksum) in the orbit array a, returning the new
// status. It panics on error. Mirrors
// gen_ufind_lin2_finalize.
func UFindLin2Finalize(a []uint32) int32 {
	var s lin2Type
	status := finalizeInitialization(a, &s)
	if status < 0 {
		panic(lin2Panic("UFindLin2Finalize", status))
	}
	return status
}

// lin2Check is the comma-error internal form shared by
// UFindLin2Check and UFindLin2CheckFinalized. Mirrors
// lin2_check.
func lin2Check(a []uint32, lenA, chksum uint32) int32 {
	var s lin2Type
	if lenA <= lin2LenHeader {
		return lin2Error(a, errGenUfindIntLin2-13)
	}
	status := loadLin2Info(a, &s)
	if status < 0 {
		return status
	}
	if s.n == 0 || s.n > lin2MaxN {
		return errGenUfindLin2Dim
	}
	if s.nG > lin2MaxNG {
		return errGenUfindLin2Gen
	}
	genSize := lin2GeneratorSize(s.n, s.nG)
	var aSize uint64
	if status == lin2Compressed {
		aSize = uint64(lin2LenHeader + 2*s.nOrbits + s.nVectors + genSize + 2)
	} else {
		aSize = uint64(lin2LenHeader) + (uint64(2) << s.n) + uint64(genSize) + 2
	}
	if aSize > uint64(lenA) {
		return lin2Error(a, errGenUfindIntLin2-15)
	}
	if chksum == 0 {
		return int32(aSize)
	}
	if status < lin2MaxStatus {
		return errGenUfindIntLin2 - 43
	}
	if a[aSize-2] != magicContent(a) {
		return errGenUfindIntLin2 - 45
	}
	var aSum uint32
	for i := uint64(0); i < aSize; i++ {
		aSum += a[i]
	}
	if aSum != 0 {
		return errGenUfindIntLin2 - 46
	}
	return int32(aSize)
}

// UFindLin2Check performs consistency checks on the
// orbit array a (allocated length lenA), returning a
// nonnegative value if the data appear consistent. It
// panics on a negative error; in that case the array
// must not be used. Mirrors gen_ufind_lin2_check.
func UFindLin2Check(a []uint32, lenA uint32) int32 {
	status := lin2Check(a, lenA, 0)
	if status < 0 {
		panic(lin2Panic("UFindLin2Check", status))
	}
	return status
}

// UFindLin2CheckFinalized checks whether the orbit array
// a (allocated length lenA) has been finalized by
// UFindLin2Finalize, returning the actual array size if
// so. It panics on a negative error. Mirrors
// gen_ufind_lin2_check_finalized.
func UFindLin2CheckFinalized(a []uint32, lenA uint32) int32 {
	status := lin2Check(a, lenA, 1)
	if status < 0 {
		panic(lin2Panic("UFindLin2CheckFinalized", status))
	}
	return status
}

// UFindLin2GetMap computes the mapping from each vector
// in V to a representative of its orbit and writes it
// into the slice map_ (length lMap >= 1 << n),
// returning 1 << n. It panics on error, e.g. if the
// array is compressed or map_ is too short. Mirrors
// gen_ufind_lin2_get_map.
func UFindLin2GetMap(a []uint32, map_ []uint32, lMap uint32) int32 {
	var s lin2Type
	status := finalizeInitialization(a, &s)
	if status < 0 {
		panic(lin2Panic("UFindLin2GetMap", status))
	}
	if status == lin2Compressed {
		panic(lin2Panic("UFindLin2GetMap", errGenUfindState))
	}
	loadLin2Info(a, &s)
	if checkOutBuf32(map_, lMap, uint32(1)<<s.n) != 0 {
		panic(lin2Panic("UFindLin2GetMap", errGenUfindOutShort))
	}
	for i := uint32(0); i < (uint32(1) << s.n); i++ {
		v := s.pT[i]
		if (v & 0xff000000) == 0xfe000000 {
			map_[i] = i
		} else {
			map_[i] = v & 0xffffff
		}
	}
	return int32(uint32(1) << s.n)
}

// UFindLin2GetTable copies the main Schreier-vector
// table from the orbit array a into the slice t (length
// lT >= 1 << n) as is, returning 1 << n. It panics on
// error, e.g. if the array is compressed or t is too
// short. Mirrors gen_ufind_lin2_get_table.
func UFindLin2GetTable(a []uint32, t []uint32, lT uint32) int32 {
	var s lin2Type
	status := finalizeInitialization(a, &s)
	if status < 0 {
		panic(lin2Panic("UFindLin2GetTable", status))
	}
	if status == lin2Compressed {
		panic(lin2Panic("UFindLin2GetTable", errGenUfindState))
	}
	if checkOutBuf32(t, lT, uint32(1)<<s.n) != 0 {
		panic(lin2Panic("UFindLin2GetTable", errGenUfindOutShort))
	}
	copy(t[:uint32(1)<<s.n], s.pT[:uint32(1)<<s.n])
	return int32(uint32(1) << s.n)
}

// UFindLin2Orbits outputs the orbit partition of the
// orbit array a in the union-find layout: t (length
// lT = 1 << n) receives the concatenated orbit members,
// and x (length lX = nOrbits + 1) receives the start
// offsets, returning the number of orbits. It panics on
// error. Mirrors gen_ufind_lin2_orbits.
func UFindLin2Orbits(a []uint32, t []uint32, lT uint32, x []uint32, lX uint32) int32 {
	var s lin2Type
	status := finalizeInitialization(a, &s)
	if status < 0 {
		panic(lin2Panic("UFindLin2Orbits", status))
	}
	if status == lin2Compressed {
		panic(lin2Panic("UFindLin2Orbits", errGenUfindState))
	}
	if checkOutBuf32(t, lT, uint32(1)<<s.n) != 0 {
		panic(lin2Panic("UFindLin2Orbits", errGenUfindOutShort))
	}
	if checkOutBuf32(x, lX, s.nOrbits+1) != 0 {
		panic(lin2Panic("UFindLin2Orbits", errGenUfindOutShort))
	}
	for i := uint32(0); i < (uint32(1) << s.n); i++ {
		t[i] = s.pO[i] & 0xffffff
	}
	x[0] = 0
	for i := uint32(0); i < s.nOrbits; i++ {
		d := readLengthInfo(s.pO[x[i]:])
		if d < 0 {
			panic(lin2Panic("UFindLin2Orbits", errGenUfindIntLin2-51))
		}
		x[i+1] = x[i] + uint32(d)
	}
	if x[s.nOrbits] != (uint32(1) << s.n) {
		panic(lin2Panic("UFindLin2Orbits", errGenUfindIntLin2-52))
	}
	return int32(s.nOrbits)
}

// lin2Panic builds the panic message for a negative
// status returned by a UFindLin2* operation.
func lin2Panic(fn string, status int32) string {
	return "cgt: " + fn + ": error status " + int32ToDec(status)
}

// u32 converts a signed int32 to uint32 at runtime,
// avoiding the constant-overflow error when a negative
// error code must be stored in a uint32 array slot.
func u32(v int32) uint32 {
	return uint32(v)
}

// int32ToDec renders a signed int32 in decimal without
// pulling in strconv at every call site.
func int32ToDec(v int32) string {
	neg := v < 0
	u := uint32(v)
	if neg {
		u = uint32(-v)
	}
	var buf [11]byte
	i := len(buf)
	if u == 0 {
		i--
		buf[i] = '0'
	}
	for u != 0 {
		i--
		buf[i] = byte('0' + u%10)
		u /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}
