package main

import (
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"strings"

	"patel.codes/cgt/_api/spec"
)

// emitSkeletons writes oracle-comparison test skeletons for the top o.top
// priority groups into the staging directory o.emit. The top groups are
// coalesced by routed package into ONE file per package: the shared-harness
// driver wiring (drv, oracle*) is package-scoped, so two same-package groups
// (e.g. reduce's free funcs and its GtWord methods) must share one file or
// their wiring collides on rename. Empty groups (e.g. swar's standing marker)
// are reported and skipped. With o.dryRun it prints the files instead. The
// staging directory is created if absent; files land there, never in the
// routed packages.
func emitSkeletons(o opts, groups []Group, s *spec.Spec, out io.Writer) error {
	ctors := constructors(s)

	top := groups
	if len(top) > o.top {
		top = top[:o.top]
	}

	// Coalesce the chosen groups by package, preserving the priority order in
	// which each package and each of its groups first appears.
	files := map[string]*pkgFile{}
	var order []string
	for _, g := range top {
		if len(g.Entries) == 0 {
			fmt.Fprintf(out, "skip empty group %s (standing marker, no entries to scaffold)\n", groupLabel(g))
			continue
		}
		pf, ok := files[g.Package]
		if !ok {
			pf = &pkgFile{pkg: g.Package, goPackage: g.GoPackage}
			files[g.Package] = pf
			order = append(order, g.Package)
		}
		pf.groups = append(pf.groups, g)
	}

	if !o.dryRun {
		if err := os.MkdirAll(o.emit, 0o755); err != nil {
			return fmt.Errorf("creating staging dir %s: %w", o.emit, err)
		}
	}

	for _, name := range order {
		pf := files[name]
		path := filepath.Join(o.emit, pf.pkg+"_oracle_test.go.txt")
		src, err := renderPackage(pf, s, ctors)
		if err != nil {
			return fmt.Errorf("rendering package %s: %w", pf.pkg, err)
		}
		if o.dryRun {
			fmt.Fprintf(out, "=== %s (%d entries) ===\n%s\n", path, pf.entryCount(), src)
			continue
		}
		if err := os.WriteFile(path, []byte(src), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
		fmt.Fprintf(out, "wrote %s (%d entries)\n", path, pf.entryCount())
	}
	return nil
}

// pkgFile collects every chosen group of one routed package into a single
// staged skeleton file, so the package-scoped harness wiring is emitted once.
type pkgFile struct {
	pkg       string
	goPackage string
	groups    []Group // in priority order
}

// entryCount totals the entries across the file's groups.
func (pf *pkgFile) entryCount() int {
	n := 0
	for _, g := range pf.groups {
		n += len(g.Entries)
	}
	return n
}

// groupLabel is a human-readable identifier for a group.
func groupLabel(g Group) string {
	if g.Recv != "" {
		return g.Package + "." + g.Recv
	}
	return g.Package
}

// renderPackage produces the gofmt-clean source of a package's skeleton file:
// a header, the package-scoped harness driver wiring emitted once, then one
// TestOracle_* function per entry across the file's groups in priority order.
func renderPackage(pf *pkgFile, s *spec.Spec, ctors map[string]spec.Func) (string, error) {
	var b strings.Builder
	writeHeader(&b, pf)
	writeDriver(&b, pf)
	for _, g := range pf.groups {
		for _, e := range g.Entries {
			writeTest(&b, g, e, s, ctors)
		}
	}
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("gofmt: %w\n--- source ---\n%s", err, b.String())
	}
	return string(formatted), nil
}

// writeHeader writes the generated-file banner and package clause. The
// skeleton is an in-package test so it can reference unexported cgt symbols
// and the package's own constructors.
func writeHeader(b *strings.Builder, pf *pkgFile) {
	fmt.Fprintf(b, `// Code generated by cmd/queue from the Me1 coverage matrix. STAGING SKELETON.
//
// This file is an oracle-parity test skeleton for the impl-but-untested
// entries in package %s. It is parked in a staging area, NOT in the routed
// package: an implementer task must claim it, fill in real inputs and
// assertions, and rename it into %s before it builds. Each test pins one cgt
// symbol to the mmgroup oracle via the Td1 shared harness.

package %s
`, pf.pkg, pf.goPackage, packageClause(pf.goPackage))
}

// packageClause is the Go package name the staged test declares: the last
// path element of the routed import path (the package the test joins once
// moved in). Every routed package — including monster, the flat top-level
// package at patel.codes/cgt/monster — is named after its final path element.
func packageClause(goPackage string) string {
	return filepath.Base(goPackage)
}

// writeDriver writes the imports and the shared-harness driver wiring, once
// per file. Lead packages have no dedicated oracle preamble yet, so the Basic
// preamble is the default; an implementer swaps in a richer preamble (e.g.
// Mat24) if the expressions need lazily-bound module globals.
func writeDriver(b *strings.Builder, pf *pkgFile) {
	fmt.Fprintf(b, `
import (
	"testing"

	oraclepkg "patel.codes/cgt/internal/oracle"
)

// drv runs mmgroup oracle expressions for the %s tests.
// TODO: switch to a richer preamble (e.g. oraclepkg.Mat24) if the oracle
// expressions below need lazily-bound module globals.
var drv = oraclepkg.New(oraclepkg.Basic)

func oracle(t *testing.T, expr string) string      { return drv.String(t, expr) }
func oracleInt(t *testing.T, expr string) int64    { return drv.Int(t, expr) }
func oracleUint(t *testing.T, expr string) uint64  { return drv.Uint(t, expr) }
func oracleInts(t *testing.T, expr string) []int64 { return drv.Ints(t, expr) }
func oracleBool(t *testing.T, expr string) bool    { return drv.Bool(t, expr) }

// Keep every typed helper referenced so the staged file builds once renamed,
// before an implementer has wired each into a real comparison.
var _ = []any{oracle, oracleInt, oracleUint, oracleInts, oracleBool}
`, pf.pkg)
}

// writeTest writes one TestOracle_* function for an entry. The body constructs
// the receiver (via its planned New<Recv>, when the spec defines one),
// supplies zero-value arguments, calls the symbol, and leaves a TODO to
// compare against the oracle expression built from the entry's py provenance.
func writeTest(b *strings.Builder, g Group, e Entry, s *spec.Spec, ctors map[string]spec.Func) {
	fn := lookupFunc(s, g, e)
	testName := "TestOracle_" + capitalize(g.Package) + "_" + e.Name
	fmt.Fprintf(b, "\nfunc %s(t *testing.T) {\n", testName)
	fmt.Fprintf(b, "\tt.Skip(\"oracle skeleton: fill in inputs and assertion\")\n")

	if e.TypeRecovery != "none" {
		fmt.Fprintf(b, "\t// Type recovery needed (%s): the spec return type is blank.\n", e.TypeRecovery)
		if e.TypeRecovery == "void-inversion" {
			fmt.Fprintf(b, "\t// C2: correlated C return is void; this symbol returns nothing.\n")
		}
		fmt.Fprintf(b, "\t// Fill goes through the _api generator, not this test.\n")
	}

	recvVar := ""
	if g.Recv != "" {
		recvVar = "recv"
		if ctor, ok := ctors[g.Recv]; ok {
			fmt.Fprintf(b, "\t// TODO: supply real arguments to the constructor.\n")
			fmt.Fprintf(b, "\t%s := %s(%s) // planned constructor for %s\n",
				recvVar, ctor.Name, zeroArgs(ctor.Params), g.Recv)
		} else {
			fmt.Fprintf(b, "\t// TODO: no New%s constructor in spec; construct %s manually.\n",
				g.Recv, g.Recv)
			fmt.Fprintf(b, "\tvar %s *%s\n", recvVar, g.Recv)
		}
	}

	args := ""
	if fn != nil {
		args = zeroArgs(fn.Params)
	}
	fmt.Fprintf(b, "\t// TODO: replace zero-value args with a real test case.\n")
	if g.Recv != "" {
		fmt.Fprintf(b, "\tgot := %s.%s(%s)\n", recvVar, e.Name, args)
	} else {
		fmt.Fprintf(b, "\tgot := %s(%s)\n", e.Name, args)
	}
	fmt.Fprintf(b, "\t_ = got\n")

	fmt.Fprintf(b, "\t// Oracle: compare got against the mmgroup expression for %s.\n", e.Py)
	fmt.Fprintf(b, "\t//   want := oracle(t, fmt.Sprintf(%q, ...))\n", e.Py+"(...)")
	fmt.Fprintf(b, "}\n")
}

// lookupFunc finds the spec entry for an emitted entry within its group, so
// the skeleton can render the call's parameter list. Returns nil when the
// entry is not found (the call is then rendered argument-free).
func lookupFunc(s *spec.Spec, g Group, e Entry) *spec.Func {
	for i := range s.Packages {
		pkg := &s.Packages[i]
		if pkg.Name != g.Package {
			continue
		}
		for j := range pkg.Funcs {
			fn := &pkg.Funcs[j]
			if fn.Name == e.Name && fn.Recv == g.Recv {
				return fn
			}
		}
	}
	return nil
}

// constructors maps a receiver type to its planned New<Recv> constructor
// entry, when the spec defines one. Mirrors cmd/oraclegen.
func constructors(s *spec.Spec) map[string]spec.Func {
	out := make(map[string]spec.Func)
	for _, fn := range s.AllFuncs() {
		if recv, ok := strings.CutPrefix(fn.Name, "New"); ok {
			if _, seen := out[recv]; !seen {
				out[recv] = fn
			}
		}
	}
	return out
}

// zeroArgs renders a comma-separated list of Go zero-value literals, one per
// parameter. Mirrors cmd/oraclegen.
func zeroArgs(params []spec.Param) string {
	if len(params) == 0 {
		return ""
	}
	parts := make([]string, len(params))
	for i, p := range params {
		parts[i] = zeroValue(p.Type)
	}
	return strings.Join(parts, ", ")
}

// zeroValue returns a Go expression evaluating to the zero value of a
// spec-named type. Mirrors cmd/oraclegen.
func zeroValue(typ string) string {
	typ = strings.TrimSpace(typ)
	switch {
	case typ == "":
		return "nil /* deferred */"
	case strings.HasPrefix(typ, "[]"), strings.HasPrefix(typ, "*"),
		strings.HasPrefix(typ, "map["), typ == "any", typ == "error":
		return "nil"
	case typ == "string":
		return `""`
	case typ == "bool":
		return "false"
	case strings.HasPrefix(typ, "int"), strings.HasPrefix(typ, "uint"),
		strings.HasPrefix(typ, "float"), typ == "byte", typ == "rune":
		return typ + "(0)"
	case strings.HasPrefix(typ, "[") && strings.Contains(typ, "]"):
		return typ + "{}"
	default:
		return typ + "{}"
	}
}

// capitalize uppercases the first byte of s. Mirrors cmd/oraclegen.
func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
