package generator

// This file ports the high-level surface of the Python
// class mmgroup.general.Orbit_Lin2 (in
// mmgroup/src/mmgroup/general/orbit_lin2.py) on top of
// the orbit-array engine in ufind_lin2.go.
//
// Orbit_Lin2 models the action of an arbitrary group G as
// a permutation group on the vector space V = GF(2)^n
// (1 <= n <= 24) via a homomorphism rho: G -> H, where H
// is a group of n x n bit matrices (optionally affine,
// v -> v*a + b) acting on V by right multiplication. The
// caller supplies a mapping function from a group element
// g to the affine bit matrix rho(g), plus a list of
// generators of G.
//
// The engine (the opaque packed orbit array) does all the
// orbit work; this layer is a thin wrapper that records
// the generators and the user-to-engine generator-index
// map, and translates Schreier-vector words back into
// words over the user's generators.

// GroupElem is the minimal interface an Orbit_Lin2
// generator must satisfy. It mirrors the Python
// requirement that a group element can be multiplied and
// raised to the powers -1 (inversion), 0 (identity) and 1.
//
// In Python the only operations Orbit_Lin2 performs on a
// group element are g * h (Mul) and g ** e for
// e in {-1, 0, 1} (Pow). A concrete provider element (such
// as the cgt monster element *MM) is adapted to this
// interface by an adapter in the consuming package.
type GroupElem interface {
	// Mul returns the product self * other.
	Mul(other GroupElem) GroupElem
	// Pow returns self raised to the integer power e.
	// Orbit_Lin2 only ever calls Pow with e in
	// {-1, 0, 1}.
	Pow(e int) GroupElem
}

// MapFunc maps a group element g to the affine bit
// transformation rho(g) on GF(2)^n. The result is a slice
// of n+1 uint32s: entries 0..n-1 are the rows of the
// n x n bit matrix a (row i is rho(g) acting on the i-th
// basis vector, encoded as an integer), and entry n is
// the affine offset b for the mapping v -> v*a + b. For a
// purely linear action b is 0.
//
// MapFunc mirrors Orbit_Lin2._map_generator: the Python
// map callable may return either a bare matrix (linear) or
// a pair (matrix, b) (affine); _map_generator appends b as
// the final entry. A Go MapFunc always returns the
// appended form, so its length is the matrix dimension n
// plus one.
type MapFunc func(g GroupElem) []uint32

// OrbitLin2 is the Go analogue of Python's Orbit_Lin2. It
// owns the packed orbit array a (see ufind_lin2.go), the
// list of group generators, the user-to-engine generator
// index map, and the mapping function.
type OrbitLin2 struct {
	a      []uint32 // packed orbit array, nil until first generator
	gen    []GroupElem
	mapGen []uint32 // engine-generator index -> index into gen
	mapFn  MapFunc

	// Cached inverses and the neutral element, populated
	// lazily by finalize() the first time a word is
	// requested. These mirror Orbit_Lin2.gen_inverse and
	// Orbit_Lin2.gen_neutral.
	genInverse []GroupElem
	genNeutral GroupElem
	finalized  bool
}

// orbitLin2MaxNGen is Orbit_Lin2.MAX_N_GEN: the hard cap
// on the number of generators the engine can store.
const orbitLin2MaxNGen = 127

// NewOrbitLin2 constructs an OrbitLin2 modelling the action
// of the group generated by generators, mapped to affine
// bit matrices by mapFn. The dimension n of V is taken
// from the length (minus one) of mapFn applied to the
// first generator; 1 <= n <= 24 must hold. mapFn may be nil
// only if generators is empty.
//
// NewOrbitLin2 panics if mapFn maps two generators to
// matrices of different dimensions, if n is out of range,
// or if more than 127 generators are supplied. It mirrors
// Orbit_Lin2.__init__ followed by _add_generator for each
// generator.
func NewOrbitLin2(mapFn MapFunc, generators []GroupElem) *OrbitLin2 {
	o := &OrbitLin2{mapFn: mapFn}
	for _, g := range generators {
		o.addGenerator(g)
	}
	return o
}

// addGenerator adds the group element g to the object,
// extending the orbit array as needed. Mirrors
// Orbit_Lin2._add_generator.
func (o *OrbitLin2) addGenerator(g GroupElem) {
	m := o.mapFn(g)
	if o.a == nil {
		o.initABuf(uint32(len(m) - 1))
	} else if uint32(len(m)) != uint32(o.Dim())+1 {
		panic("cgt: OrbitLin2: incompatible generator representations")
	}
	nGen := o.extendABuf(1)
	UFindLin2Add(o.a, m, uint32(len(m)))
	o.mapGen[nGen] = uint32(len(o.gen))
	o.gen = append(o.gen, g)
	o.finalized = false
}

// initABuf initialises the orbit array for dimension dim.
// Mirrors Orbit_Lin2._init_a_buf, including the default
// generator cap min(4*dim, MAX_N_GEN).
func (o *OrbitLin2) initABuf(dim uint32) {
	maxNGen := 4 * dim
	if maxNGen > orbitLin2MaxNGen {
		maxNGen = orbitLin2MaxNGen
	}
	aSize := UFindLin2Size(dim, maxNGen)
	o.a = make([]uint32, aSize)
	UFindLin2Init(o.a, uint32(len(o.a)), dim, maxNGen)
	o.mapGen = make([]uint32, maxNGen)
}

// extendABuf grows the orbit array so it can hold nMore
// additional generators, returning the current generator
// count. Mirrors Orbit_Lin2._extend_a_buf.
func (o *OrbitLin2) extendABuf(nMore uint32) uint32 {
	nGen := uint32(UFindLin2NGen(o.a))
	nMaxGen := uint32(UFindLin2NMaxGen(o.a))
	newNGen := nGen + nMore
	if newNGen > nMaxGen {
		newNMaxGen := 2 * nMaxGen
		if newNGen > newNMaxGen {
			newNMaxGen = newNGen
		}
		if newNMaxGen > orbitLin2MaxNGen {
			newNMaxGen = orbitLin2MaxNGen
		}
		if newNMaxGen < newNGen {
			panic(Lin2Panic("OrbitLin2.extendABuf", ErrUFindLin2Gen))
		}
		newASize := UFindLin2Size(uint32(o.Dim()), newNMaxGen)
		if uint32(len(o.a)) < uint32(newASize) {
			grown := make([]uint32, newASize)
			copy(grown, o.a)
			o.a = grown
		}
		UFindLin2Pad(o.a, uint32(newASize), newNMaxGen)
		grownMap := make([]uint32, newNMaxGen)
		copy(grownMap, o.mapGen)
		o.mapGen = grownMap
	}
	return nGen
}

// Dim returns the dimension n of the vector space GF(2)^n.
// It panics if no generators have been added. Mirrors the
// Orbit_Lin2.dim property.
func (o *OrbitLin2) Dim() int {
	if o.a == nil {
		panic("cgt: OrbitLin2: no generators present")
	}
	return int(UFindLin2Dim(o.a))
}

// Generators returns the list of generators of the group.
// Mirrors Orbit_Lin2.generators.
func (o *OrbitLin2) Generators() []GroupElem {
	return o.gen
}

// NOrbits returns the number of orbits on the vector space
// under the action of the group. It panics if no
// generators are present. Mirrors Orbit_Lin2.n_orbits.
func (o *OrbitLin2) NOrbits() int {
	o.requireA()
	return int(UFindLin2NOrbits(o.a))
}

// OrbitLin2RepresentativesResult holds the result of
// Representatives: equal-length arrays of orbit
// representatives and their orbit sizes. Mirrors the pair
// (reps, sizes) returned by Orbit_Lin2.representatives.
type OrbitLin2RepresentativesResult struct {
	Reps  []uint32
	Sizes []uint32
}

// Representatives returns an ordered list of orbit
// representatives together with the corresponding orbit
// sizes. Mirrors Orbit_Lin2.representatives.
func (o *OrbitLin2) Representatives() OrbitLin2RepresentativesResult {
	o.requireA()
	n := uint32(UFindLin2NOrbits(o.a))
	reps := make([]uint32, n)
	UFindLin2Representatives(o.a, reps, n)
	sizes := make([]uint32, n)
	UFindLin2OrbitLengths(o.a, sizes, n)
	return OrbitLin2RepresentativesResult{Reps: reps, Sizes: sizes}
}

// OrbitRep returns the representative of the orbit of the
// vector v under the action of the group. Mirrors
// Orbit_Lin2.orbit_rep.
func (o *OrbitLin2) OrbitRep(v int) int {
	o.requireA()
	return int(UFindLin2RepV(o.a, uint32(v)))
}

// OrbitSize returns the size of the orbit of the vector v.
// Mirrors Orbit_Lin2.orbit_size.
func (o *OrbitLin2) OrbitSize(v int) int {
	o.requireA()
	return int(UFindLin2LenOrbitV(o.a, uint32(v)))
}

// Orbit returns the orbit of the vector v as a slice of
// vectors (encoded as integers). Mirrors Orbit_Lin2.orbit.
func (o *OrbitLin2) Orbit(v int) []uint32 {
	o.requireA()
	size := uint32(UFindLin2LenOrbitV(o.a, uint32(v)))
	r := make([]uint32, size)
	UFindLin2OrbitV(o.a, uint32(v), r, size)
	return r
}

// MulVG returns the product of the vector v with the group
// element g, i.e. the image of v under the affine
// transformation rho(g). Mirrors Orbit_Lin2.mul_v_g.
func (o *OrbitLin2) MulVG(v int, g GroupElem) int {
	m := o.mapFn(g)
	return int(UFindLin2MulAffine(uint32(v), m, uint32(o.Dim())))
}

// OrbitLin2WordEntry is one entry of the word returned by
// MapVWordG: a reference to a user generator (by its index
// into Generators()) and a sign, +1 for the generator and
// -1 for its inverse. Mirrors the pairs
// (map_gen[x >> 1], (-1) ** x) produced by
// Orbit_Lin2.map_v_word_G.
type OrbitLin2WordEntry struct {
	Gen  int // index into Generators()
	Sign int // +1 or -1
}

// MapVWordG returns a word in the group generators that
// maps the vector v to img (default: the orbit
// representative of v when img < 0). The word is a slice of
// (generator index, sign) entries; reading them left to
// right and multiplying the corresponding generators (or
// their inverses, for sign -1) yields a group element
// taking v to img. It panics if v and img lie in different
// orbits. Mirrors Orbit_Lin2.map_v_word_G.
func (o *OrbitLin2) MapVWordG(v int, img int) []OrbitLin2WordEntry {
	w := o.mapVWordA(v, img)
	out := make([]OrbitLin2WordEntry, len(w))
	for i, x := range w {
		sign := 1
		if x&1 != 0 {
			sign = -1
		}
		out[i] = OrbitLin2WordEntry{Gen: int(o.mapGen[x>>1]), Sign: sign}
	}
	return out
}

// MapVG returns a group element mapping the vector v to
// img (default: the orbit representative of v when
// img < 0). It panics if v and img lie in different
// orbits, or if the generators do not satisfy GroupElem
// (they always do, by construction). Mirrors
// Orbit_Lin2.map_v_G.
func (o *OrbitLin2) MapVG(v int, img int) GroupElem {
	w := o.mapVWordA(v, img)
	g := o.genNeutral
	gg := [2][]GroupElem{o.gen, o.genInverse}
	for _, x := range w {
		g = g.Mul(gg[x&1][x>>1])
	}
	return g
}

// MapVGTransform applies the group element mapping v to img
// to obj by right multiplication, returning obj * h where h
// is the element MapVG would return. It is equivalent to
// MapVG(v, img) applied to obj but lets the generators act
// on obj one at a time. Mirrors
// Orbit_Lin2.map_v_G_transform.
func (o *OrbitLin2) MapVGTransform(obj GroupElem, v int, img int) GroupElem {
	w := o.mapVWordA(v, img)
	gg := [2][]GroupElem{o.gen, o.genInverse}
	for _, x := range w {
		obj = obj.Mul(gg[x&1][x>>1])
	}
	return obj
}

// mapVWordA computes the engine Schreier-vector word taking
// v to img (or to the orbit representative when img < 0).
// The returned word is a slice of engine generator indices:
// an even index 2i means generator i, an odd index 2i+1
// means the inverse of generator i. Mirrors
// Orbit_Lin2._map_v_word_a.
func (o *OrbitLin2) mapVWordA(v int, img int) []uint32 {
	o.finalize()
	// Grow the output buffer until the word fits, exactly
	// as the Python loop does (starting at 32, doubling).
	mSize := uint32(32)
	var g []uint8
	for {
		buf := make([]uint8, mSize)
		res := UFindLin2MapVRaw(o.a, uint32(v), buf, mSize)
		if res >= 0 {
			g = buf[:res]
			break
		}
		if res != ErrUFindOutShort || mSize >= 1<<uint(o.Dim()) {
			panic(Lin2Panic("OrbitLin2.mapVWordA", res))
		}
		mSize <<= 1
	}
	w := make([]uint32, len(g))
	for i, b := range g {
		w[i] = uint32(b)
	}
	if img < 0 {
		return w
	}
	if o.OrbitRep(v) != o.OrbitRep(img) {
		panic("cgt: OrbitLin2: preimage and image vector not in same orbit")
	}
	// Append the reversed, inverted word taking img to the
	// representative, so the concatenation maps v to img.
	g1 := o.mapVWordA(img, -1)
	for i := len(g1) - 1; i >= 0; i-- {
		w = append(w, g1[i]^1)
	}
	return w
}

// finalize computes the orbit array's Schreier vectors and
// the cached generator inverses / neutral element. Mirrors
// Orbit_Lin2._finalize. It panics if no generators are
// present. finalize is idempotent.
func (o *OrbitLin2) finalize() {
	if o.a == nil {
		panic("cgt: OrbitLin2: no generators present")
	}
	UFindLin2Finalize(o.a)
	if o.finalized {
		return
	}
	o.genInverse = make([]GroupElem, len(o.gen))
	for i, g := range o.gen {
		o.genInverse[i] = g.Pow(-1)
	}
	o.genNeutral = o.gen[0].Pow(0)
	o.finalized = true
}

// requireA panics if the object has no generators, matching
// the engine wrappers' precondition that a is initialised.
func (o *OrbitLin2) requireA() {
	if o.a == nil {
		panic("cgt: OrbitLin2: no generators present")
	}
}

// Compress extracts the orbits of the given vectors into a
// new, compressed OrbitLin2 sharing this object's
// generators and mapping function. Mirrors
// Orbit_Lin2.compress.
func (o *OrbitLin2) Compress(orbits []int) *OrbitLin2 {
	o.requireA()
	nGen := uint32(UFindLin2NGen(o.a))
	oo := make([]uint32, len(orbits))
	for i, v := range orbits {
		oo[i] = uint32(v)
	}
	lc := uint32(UFindLin2CompressedSize(o.a, oo, uint32(len(oo))))
	c := make([]uint32, lc)
	lc = uint32(UFindLin2Compress(o.a, oo, uint32(len(oo)), c, lc))
	res := &OrbitLin2{
		a:      c[:lc],
		gen:    append([]GroupElem(nil), o.gen...),
		mapGen: append([]uint32(nil), o.mapGen[:nGen]...),
		mapFn:  o.mapFn,
	}
	return res
}
