package main

import (
	"strings"
	"testing"
)

var cases = []struct {
	name, in, want string
}{
	{
		name: "wrap to decl width",
		in: `package p

// Alpha does a thing with words that will be wrapped to match the width of the declaration line below.
func AlphaBetaGammaDeltaEpsilonZeta(count int) {
}
`,
		want: `package p

// Alpha does a thing with words that will be
// wrapped to match the width of the declaration
// line below.
func AlphaBetaGammaDeltaEpsilonZeta(count int) {
}
`,
	},
	{
		name: "clamp to min 40",
		in: `package p

// P is tiny but its comment still gets exactly forty columns of width.
type P struct {
}
`,
		want: `package p

// P is tiny but its comment still gets
// exactly forty columns of width.
type P struct {
}
`,
	},
	{
		name: "short paragraph stays one line",
		in: `package p

// String renders m as its mode name for logs.
func (m Mode) String() string {
}
`,
		want: `package p

// String renders m as its mode name for logs.
func (m Mode) String() string {
}
`,
	},
	{
		name: "clamp to max 80",
		in: `package p

// LongOne has an extremely long declaration line but the comment must stay within eighty columns anyway because that is the cap.
func LongOne(aLongParameterName string, anotherLongParameterName string, yetAnotherOne string) {
}
`,
		want: `package p

// LongOne has an extremely long declaration line but the comment must stay
// within eighty columns anyway because that is the cap.
func LongOne(aLongParameterName string, anotherLongParameterName string, yetAnotherOne string) {
}
`,
	},
	{
		name: "structure preserved",
		in: `package p

// F does things and this leading paragraph of prose gets rewrapped to the width below.
//
//	code block stays exactly as written
//
//   - list items stay exactly as written
//
// # Heading Stays
//
//go:generate stringer -type=P
func F(a, b, c, d, e, f int) {
}
`,
		want: `package p

// F does things and this leading
// paragraph of prose gets rewrapped to
// the width below.
//
//	code block stays exactly as written
//
//   - list items stay exactly as written
//
// # Heading Stays
//
//go:generate stringer -type=P
func F(a, b, c, d, e, f int) {
}
`,
	},
	{
		name: "trailing comment untouched",
		in: `package p

func f() {
	x := 1 // this trailing comment stays put no matter how very long it happens to be
	_ = x
}
`,
		want: `package p

func f() {
	x := 1 // this trailing comment stays put no matter how very long it happens to be
	_ = x
}
`,
	},
	{
		name: "block comment untouched",
		in: `package p

/* block comments are left completely alone even when they are quite long indeed */
func f() {
}
`,
		want: `package p

/* block comments are left completely alone even when they are quite long indeed */
func f() {
}
`,
	},
	{
		name: "generated file untouched",
		in: `// Code generated by stringer. DO NOT EDIT.

package p

// This very long comment would normally be rewrapped but the file is generated.
type P struct {
}
`,
		want: `// Code generated by stringer. DO NOT EDIT.

package p

// This very long comment would normally be rewrapped but the file is generated.
type P struct {
}
`,
	},
	{
		name: "in-body comment anchors to next statement",
		in: `package p

func f() {
	// this comment wraps to the width of the statement on the following line
	callSomethingWithAModeratelyLongName(1, 2)
}
`,
		want: `package p

func f() {
	// this comment wraps to the width of the
	// statement on the following line
	callSomethingWithAModeratelyLongName(1, 2)
}
`,
	},
	{
		// Both paragraphs must wrap at the one
		// width chosen for the whole block, so
		// their right edges agree even when
		// one paragraph alone would prefer a
		// different width.
		name: "paragraphs share block width",
		in: `package p

// First paragraph of prose here is long enough that it must wrap onto several lines to fit.
//
// Second paragraph is also long enough to wrap and its lines should share the same right edge.
func AlphaBetaGammaDeltaEpsilon(count int) {
}
`,
		want: `package p

// First paragraph of prose here is long
// enough that it must wrap onto several
// lines to fit.
//
// Second paragraph is also long enough
// to wrap and its lines should share the
// same right edge.
func AlphaBetaGammaDeltaEpsilon(count int) {
}
`,
	},
	{
		// Zero-cost wraps exist at widths 40
		// (break after "dddd") and 42 (break
		// after "e"); the tie goes to the width
		// nearest the anchor target of 40.
		name: "tie goes to width nearest target",
		in: `package p

// aaaaaaaaaa bbbbbbbbbb cccccccccc dddd e ffffffffff gggggggggg iii
type P struct {
}
`,
		want: `package p

// aaaaaaaaaa bbbbbbbbbb cccccccccc dddd
// e ffffffffff gggggggggg iii
type P struct {
}
`,
	},
	{
		// The most even wrap strands "below."
		// on its own line; the widow penalty
		// prefers the fuller last line.
		name: "widow avoided",
		in: `package p

// F does things and this leading paragraph of prose gets rewrapped to the width below.
func F(a, b, c, d, e, f int) {
}
`,
		want: `package p

// F does things and this leading
// paragraph of prose gets rewrapped to
// the width below.
func F(a, b, c, d, e, f int) {
}
`,
	},
	{
		name: "short comment joins up",
		in: `package p

// Parts holds
// system prompt
// components.
type Parts struct {
}
`,
		want: `package p

// Parts holds system prompt components.
type Parts struct {
}
`,
	},
}

func format(t *testing.T, src string) string {
	t.Helper()
	out, err := process("test.go", []byte(src))
	if err != nil {
		t.Fatal(err)
	}
	return string(out)
}

func TestGolden(t *testing.T) {
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := format(t, c.in)
			if got != c.want {
				t.Errorf("got:\n%s\nwant:\n%s", got, c.want)
			}
		})
	}
}

func TestIdempotent(t *testing.T) {
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			once := format(t, c.in)
			twice := format(t, once)
			if once != twice {
				t.Errorf("not idempotent:\nonce:\n%s\ntwice:\n%s", once, twice)
			}
		})
	}
}

// words is the file's token stream
// ignoring layout: whitespace and the
// "//" markers (their count changes
// when lines rebreak).
func words(src string) []string {
	var w []string
	for _, f := range strings.Fields(src) {
		if f == "//" {
			continue
		}
		w = append(w, strings.TrimPrefix(f, "// "))
	}
	return w
}

// TestWordsPreserved checks the formatter
// only moves whitespace: the word
// sequence of the whole file is identical
// before and after.
func TestWordsPreserved(t *testing.T) {
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			in := words(c.in)
			out := words(format(t, c.in))
			if strings.Join(in, " ") != strings.Join(out, " ") {
				t.Errorf("word stream changed:\nin:  %v\nout: %v", in, out)
			}
		})
	}
}

func TestWrapWordsWidth(t *testing.T) {
	words := strings.Fields("one two three four five six seven eight nine ten eleven twelve thirteen")
	for _, width := range []int{10, 20, 37, 77} {
		wrapped, _ := wrapWords(words, width)
		for i, line := range wrapped {
			if n := len(line); n > width {
				t.Errorf("width %d line %d: %q is %d cols", width, i, line, n)
			}
		}
	}
}

// TestWrapWordsCost checks the returned
// cost is the metric the caller ranks
// candidate widths by: summed squared
// deviation from width over every line
// but the last, which is free when it
// fits.
func TestWrapWordsCost(t *testing.T) {
	words := strings.Fields("one two three four five six seven eight nine ten eleven twelve thirteen")
	for _, width := range []int{10, 20, 37, 77} {
		wrapped, cost := wrapWords(words, width)
		sum := 0
		for _, line := range wrapped[:len(wrapped)-1] {
			d := width - len(line)
			sum += d * d
		}
		if sum != cost {
			t.Errorf("width %d: cost %d, recomputed %d", width, cost, sum)
		}
	}
}

// TestNoOvershoot checks the hard cap:
// no rewrapped prose line may exceed
// maxCols regardless of jitter, since
// candidate widths are clamped there.
// Verbatim structure lines are exempt
// but none of the cases has a long one.
func TestNoOvershoot(t *testing.T) {
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			for _, line := range strings.Split(format(t, c.in), "\n") {
				if strings.HasPrefix(strings.TrimLeft(line, " \t"), "//") && len(line) > maxCols {
					t.Errorf("comment line %d cols: %q", len(line), line)
				}
			}
		})
	}
}
